### ISSUE TITLE
ttempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference

### ISSUE THREAD

**Issue by ubheamar** [transistorsoft/flutter_background_fetch#10]
2019-02-04 21:51:12.201 31983-31983/com.webstersys.touch E/EventBus: Could not dispatch event: class com.transistorsoft.locationmanager.event.HeadlessEvent to subscribing class class com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask
    java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
        at com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask.initFlutterView(HeadlessTask.java:164)
        at com.transistorsoft.flutter.backgroundgeolocation.HeadlessTask.onHeadlessEvent(HeadlessTask.java:91)
        at java.lang.reflect.Method.invoke(Native Method)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:485)
        at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:479)
        at org.greenrobot.eventbus.HandlerPoster.handleMessage(HandlerPoster.java:67)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2019-02-04 21:51:12.201 31983-31983/com.webstersys.touch D/EventBus: No subscribers registered for

**Comment by ubheamar** [comment]
when i ran adb shell cmd jobscheduler run -f com.webstersys.touch 999 
command i get this issue

**Comment by christocracy** [comment]
Did you get this from running the `/example` in this repo?

**Comment by ubheamar** [comment]
yes this my application & as well as your /example having the same issue

**Comment by christocracy** [comment]
What version of `background_fetch` do you have installed?

**Comment by christocracy** [comment]
Also, your error is not related to `background_fetch`, it's related to [`flutter_background_geolocation`](https://github.com/transistorsoft/flutter_background_geolocation)

**Comment by ubheamar** [comment]
Okay i am not so much clear about these 2 plugins why background fetch plugin is there 

Currently i am using both plugins 
What i want to do is:
Tracking geofence forground & background 
Frontend working fine with flutter background geolocation plugin 
For background geofence event do i need to use background_fetch plugin ?

**Comment by ubheamar** [comment]
Geofence event not working after app gets killed

**Comment by ubheamar** [comment]
About issue i think yes its issue with geolocation plugin

**Comment by christocracy** [comment]
This repo does not implement geofences.  This is the background_fetch repo.  If you issue with geofencing, post an issue at background_geolocation repo.
