### ISSUE TITLE
Headless Task keeps stopping Application

### ISSUE THREAD

**Issue by mamen2022** [transistorsoft/flutter_background_fetch#11]
Hi,
I followed the tutorial and the Android setup, but something weird is happening.
When i run the script "simulate-fetch" with the App opened, the plugin works ok, but if I close my App and run the script again, I get a dialog that "App keeps Stopping" and the background task do not run.
In the example provided it runs flawlessly. 
I changed the AndroidManifest, created the Application.java and changed my main.dart according to the example, and even tried to completely copy the main.dart from the example. But still no success.
I am running the App on the Android Studio Emulator, but also tested on a smartphone (same result).

On the logcat, with the app opened i get this when I ran the script (I assume that is correct):
```
02-12 18:45:37.114 22134 22134 D TSBackgroundFetch: - Background Fetch event received
02-12 18:45:37.128 22134 22153 I flutter : [BackgroundFetch] Event received
02-12 18:45:37.151 22134 22134 D TSBackgroundFetch: - finish
02-12 18:45:37.151 22134 22134 D TSBackgroundFetch: - jobFinished
```

When the app is closed the task just stops with no error or anything:
```
02-12 18:41:42.236 21985 21985 D TSBackgroundFetch: - Background Fetch event received
02-12 18:41:42.247 21985 21985 D TSBackgroundFetch: - finish
02-12 18:41:42.247 21985 21985 D TSBackgroundFetch: - jobFinished
02-12 18:41:42.266 21985 21985 D TSBackgroundFetch: HeadlessJobService onStartJob
02-12 18:41:42.266 21985 21985 D TSBackgroundFetch: 💀 [HeadlessTask]
```

On the example app i get this:
```
02-12 18:42:24.917 21105 21105 D TSBackgroundFetch: - Background Fetch event received
02-12 18:42:24.919 21105 21105 D TSBackgroundFetch: - finish
02-12 18:42:24.919 21105 21105 D TSBackgroundFetch: - jobFinished
02-12 18:42:24.955 21105 21105 D TSBackgroundFetch: HeadlessJobService onStartJob
02-12 18:42:24.955 21105 21105 D TSBackgroundFetch: 💀 [HeadlessTask]
02-12 18:42:25.049 21105 21139 I flutter : [BackgroundFetch] Headless event received.
02-12 18:42:25.073 21105 21105 D TSBackgroundFetch: - finish
02-12 18:42:25.073 21105 21105 D TSBackgroundFetch: HeadlessJobService jobFinished
```

On my app, the code just stops at 💀 [HeadlessTask] ..

When I start my app I get this. The jobService var is correct or should be different according to my app settings? Its related to my problem? 
```
02-12 18:43:31.460 22134 22134 D TSBackgroundFetch: - configure: {
02-12 18:43:31.460 22134 22134 D TSBackgroundFetch:   "minimumFetchInterval": 15,
02-12 18:43:31.460 22134 22134 D TSBackgroundFetch:   "stopOnTerminate": false,
02-12 18:43:31.460 22134 22134 D TSBackgroundFetch:   "startOnBoot": true,
02-12 18:43:31.460 22134 22134 D TSBackgroundFetch:   "forceReload": false,
02-12 18:43:31.460 22134 22134 D TSBackgroundFetch:   "jobService": "com.transistorsoft.flutter.backgroundfetch.HeadlessJobService"
02-12 18:43:31.460 22134 22134 D TSBackgroundFetch: }
02-12 18:43:31.460 22134 22134 D TSBackgroundFetch: - start
02-12 18:43:32.003 22134 22153 I flutter : [BackgroundFetch] SUCCESS: 2
```

**Comment by christocracy** [comment]
You followed the [Android Setup](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md)?

I think there's a slight mistake in the `Application.java`.  Show me your custom `Application.java`

**Comment by christocracy** [comment]
The [Application.java](https://github.com/transistorsoft/flutter_background_fetch/blob/master/example/android/app/src/main/java/com/transistorsoft/flutter/backgroundfetch/backgroundfetchexample/Application.java) in `/example` folder is correct.

**Comment by mamen2022** [comment]
```
package com.example.myapp;

import com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin;
import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class Application extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {
 @Override
 public void onCreate() {
   super.onCreate();
   BackgroundFetchPlugin.setPluginRegistrant(this);
 }

 @Override
 public void registerWith(PluginRegistry registry) {
   GeneratedPluginRegistrant.registerWith(registry);
 }
}
```

**Comment by christocracy** [comment]
Your `Application.java` looks fine.

**Comment by christocracy** [comment]
Show me your `dart` code.

**Comment by christocracy** [comment]
>The jobService var is correct

`jobService` is set automatically.  You don't deal with this.

**Comment by mamen2022** [comment]
```
const EVENTS_KEY = "fetch_events";

/// This "Headless Task" is run when app is terminated.
void backgroundFetchHeadlessTask() async {
  print('[BackgroundFetch] Headless event received.');

  SharedPreferences prefs = await SharedPreferences.getInstance();

  // Read fetch_events from SharedPreferences
  List<String> events = [];
  String json = prefs.getString(EVENTS_KEY);
  if (json != null) {
    events = jsonDecode(json).cast<String>();
  }
  // Add new event.
  events.insert(0, new DateTime.now().toString() + ' [Headless]');
  // Persist fetch events in SharedPreferences
  prefs.setString(EVENTS_KEY, jsonEncode(events));

  BackgroundFetch.finish();
}

void main() {
  AppConfig.fromJsonFile().then((onValue) {
    if (onValue == null) {
      log("Error - Configurations invalid");
      return;
    }
    AppConfig configuredApp = onValue;

    _configRoutes();
    _configEnvironment(configuredApp);
    runApp(configuredApp);

    // Register to receive BackgroundFetch events after app is terminated.
    // Requires {stopOnTerminate: false, enableHeadless: true}
    BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
  }).catchError((onError) {
    log(onError);
  });
}

void _configRoutes() {
  Navigation.initPaths();
}

/// Sets the app's configurations at non-widget files.
void _configEnvironment(AppConfig configuredApp) {
  // for the form utilitaries
  formUtils.setEnv(configuredApp);

  // for the error messages
  RC.appConfig = configuredApp;
  SC.appConfig = configuredApp;
  APP.appConfig = configuredApp;

  // for Api messages
  UserService.appConfig = configuredApp;
  EvStationsService.appConfig = configuredApp;
  PayService.appConfig = configuredApp;
  HmiService.appConfig = configuredApp;
}

class MobileApp extends StatefulWidget {
  @override
  _MobileAppState createState() => new _MobileAppState();
}

class _MobileAppState extends State<MobileApp> {
  bool _enabled = true;
  int _status = 0;
  List<String> _events = [];

  @override
  void initState() {
    super.initState();
    initPlatformState();
  }

  // Platform messages are asynchronous, so we initialize in an async method.
  Future<void> initPlatformState() async {
    // Load persisted fetch events from SharedPreferences
    SharedPreferences prefs = await SharedPreferences.getInstance();
    String json = prefs.getString(EVENTS_KEY);
    if (json != null) {
      setState(() {
        _events = jsonDecode(json).cast<String>();
      });
    }

    // Configure BackgroundFetch.
    BackgroundFetch.configure(
            BackgroundFetchConfig(
                minimumFetchInterval: 15,
                stopOnTerminate: false,
                enableHeadless: true,
                forceReload: false,
                startOnBoot: true),
            _onBackgroundFetch)
        .then((int status) {
      print('[BackgroundFetch] SUCCESS: $status');
      setState(() {
        _status = status;
      });
    }).catchError((e) {
      print('[BackgroundFetch] ERROR: $e');
      setState(() {
        _status = e;
      });
    });

    // Optionally query the current BackgroundFetch status.
    int status = await BackgroundFetch.status;
    setState(() {
      _status = status;
    });

    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;
  }

  void _onBackgroundFetch() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();

    // This is the fetch-event callback.
    print('[BackgroundFetch] Event received');
    setState(() {
      _events.insert(0, new DateTime.now().toString());
    });
    // Persist fetch events in SharedPreferences
    prefs.setString(EVENTS_KEY, jsonEncode(_events));

    // IMPORTANT:  You must signal completion of your fetch task or the OS can punish your app
    // for taking too long in the background.
    BackgroundFetch.finish();
  }

  /*void _onClickEnable(enabled) {
    setState(() {
      _enabled = enabled;
    });
    if (enabled) {
      BackgroundFetch.start().then((int status) {
        print('[BackgroundFetch] start success: $status');
      }).catchError((e) {
        print('[BackgroundFetch] start FAILURE: $e');
      });
    } else {
      BackgroundFetch.stop().then((int status) {
        print('[BackgroundFetch] stop success: $status');
      });
    }
  }

  void _onClickStatus() async {
    int status = await BackgroundFetch.status;
    print('[BackgroundFetch] status: $status');
    setState(() {
      _status = status;
    });
  }

  void _onClickClear() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    prefs.remove(EVENTS_KEY);
    setState(() {
      _events = [];
    });
  }*/

  /*@override
  Widget build(BuildContext context) {
    const EMPTY_TEXT = Center(
        child: Text(
            'Waiting for fetch events.  Simulate one.\n [Android] \$ ./scripts/simulate-fetch\n [iOS] XCode->Debug->Simulate Background Fetch'));

    return new MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(
            title: const Text('BackgroundFetch Example',
                style: TextStyle(color: Colors.black)),
            backgroundColor: Colors.amberAccent,
            brightness: Brightness.light,
            actions: <Widget>[
              Switch(value: _enabled, onChanged: _onClickEnable),
            ]),
        body: (_events.isEmpty)
            ? EMPTY_TEXT
            : Container(
                child: new ListView.builder(
                    itemCount: _events.length,
                    itemBuilder: (BuildContext context, int index) {
                      String timestamp = _events[index];
                      return InputDecorator(
                          decoration: InputDecoration(
                              contentPadding: EdgeInsets.only(
                                  left: 5.0, top: 5.0, bottom: 5.0),
                              labelStyle:
                                  TextStyle(color: Colors.blue, fontSize: 20.0),
                              labelText: "[background fetch event]"),
                          child: new Text(timestamp,
                              style: TextStyle(
                                  color: Colors.black, fontSize: 16.0)));
                    }),
              ),
        bottomNavigationBar: BottomAppBar(
            child: Container(
                padding: EdgeInsets.only(left: 5.0, right: 5.0),
                child: Row(
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    children: <Widget>[
                      RaisedButton(
                          onPressed: _onClickStatus,
                          child: Text('Status: $_status')),
                      RaisedButton(
                          onPressed: _onClickClear, child: Text('Clear'))
                    ]))),
      ),
    );
  }*/

  @override
  Widget build(BuildContext context) {
    var appConfig = AppConfig.of(context);

    ApiGlobals.SERVER_URL = appConfig.apiBaseUrl;

    return new MaterialApp(
        title: appConfig.appName,
        onGenerateRoute: Navigation.router.generator,
        theme: ThemeData(
          primaryColor: appConfig.primary_dark,
          fontFamily: "Patron",
          bottomAppBarColor: appConfig.grey_light,
          selectedRowColor: appConfig.grey,
          accentColor: appConfig.primary_light,
          backgroundColor: appConfig.grey_light,
          buttonColor: appConfig.primary_dark,
          cardColor: Colors.white,
          disabledColor: appConfig.grey,
          errorColor: Colors.red,
          hintColor: appConfig.grey_dark,
          colorScheme: ColorScheme(
              onPrimary: Colors.white,
              onSecondary: Colors.white,
              onError: Colors.red,
              onSurface: appConfig.grey_light,
              onBackground: Colors.black,
              primary: appConfig.primary,
              secondary: appConfig.primary_light,
              error: appConfig.grey_light,
              surface: appConfig.primary,
              background: appConfig.grey_light,
              primaryVariant: appConfig.primary_dark,
              secondaryVariant: appConfig.grey_dark,
              brightness: Brightness.dark),
        ),
        home: splash.SplashScreenPage(),
        localizationsDelegates: [
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
        ],
        supportedLocales: [
          const Locale('en', 'US'),
          const Locale('pt', 'PT'),
        ]);
  }
}
```

**Comment by christocracy** [comment]
>I get a dialog that "App keeps Stopping"

There should be a stacktrace in logcat.

```
$ adb logcat
```

**Comment by mamen2022** [comment]
But I had also replaced my main.dart for the example one.
And still the same behavior and no success. I don't think that the problem is there

**Comment by mamen2022** [comment]
I ran ´´´adb logcat *:S flutter:V, TSBackgroundFetch:V´´´ and no errors at all..

**Comment by christocracy** [comment]
No, you need *unfiltered* logcat to see stacktrace.

**Comment by christocracy** [comment]
And in the meantime, show me your:
```
$ flutter --version
$ flutter doctor
```

**Comment by mamen2022** [comment]
Yes I get it!

```
02-12 19:03:18.746 22523 22523 D TSBackgroundFetch: - Background Fetch event received
02-12 19:03:18.759 22523 22523 D TSBackgroundFetch: - finish
02-12 19:03:18.759 22523 22523 D TSBackgroundFetch: - jobFinished
02-12 19:03:18.780 22523 22523 D TSBackgroundFetch: HeadlessJobService onStartJob
02-12 19:03:18.780 22523 22523 D TSBackgroundFetch: 💀 [HeadlessTask]
02-12 19:03:18.873 22523 22523 E JobServiceEngine: Error while executing job: 998
02-12 19:03:18.873 22523 22523 D AndroidRuntime: Shutting down VM
02-12 19:03:18.874 22523 22523 E AndroidRuntime: FATAL EXCEPTION: main
02-12 19:03:18.874 22523 22523 E AndroidRuntime: Process: com.example.mobileve, PID: 22523
02-12 19:03:18.874 22523 22523 E AndroidRuntime: java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference
02-12 19:03:18.874 22523 22523 E AndroidRuntime: 	at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:112)
02-12 19:03:18.874 22523 22523 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-12 19:03:18.874 22523 22523 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
02-12 19:03:18.874 22523 22523 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
02-12 19:03:18.874 22523 22523 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-12 19:03:18.874 22523 22523 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-12 19:03:18.874 22523 22523 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
02-12 19:03:18.874 22523 22523 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference
02-12 19:03:18.874 22523 22523 E AndroidRuntime: 	at com.pauldemarco.flutterblue.FlutterBluePlugin.<init>(FlutterBluePlugin.java:94)
02-12 19:03:18.874 22523 22523 E AndroidRuntime: 	at com.pauldemarco.flutterblue.FlutterBluePlugin.registerWith(FlutterBluePlugin.java:82)
02-12 19:03:18.874 22523 22523 E AndroidRuntime: 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:26)
02-12 19:03:18.874 22523 22523 E AndroidRuntime: 	at com.example.mobileve.Application.registerWith(Application.java:17)
02-12 19:03:18.874 22523 22523 E AndroidRuntime: 	at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.initFlutterView(HeadlessTask.java:133)
02-12 19:03:18.874 22523 22523 E AndroidRuntime: 	at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.<init>(HeadlessTask.java:47)
02-12 19:03:18.874 22523 22523 E AndroidRuntime: 	at com.transistorsoft.flutter.backgroundfetch.HeadlessJobService.onStartJob(HeadlessJobService.java:38)
02-12 19:03:18.874 22523 22523 E AndroidRuntime: 	at android.app.job.JobService$1.onStartJob(JobService.java:62)
02-12 19:03:18.874 22523 22523 E AndroidRuntime: 	at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)
02-12 19:03:18.874 22523 22523 E AndroidRuntime: 	... 6 more
02-12 19:03:18.888 22523 22523 I Process : Sending signal. PID: 22523 SIG: 9
02-12 19:03:18.950  1723  1723 I Zygote  : Process 22523 exited due to signal (9)
02-12 19:03:18.950  1884  1982 I ActivityManager: Process com.example.mobileve (pid 22523) has died: vis  TRNB
02-12 19:03:18.950  1884  1982 W ActivityManager: Scheduling restart of crashed service com.example.mobileve/com.transistorsoft.flutter.backgroundfetch.HeadlessJobService in 1000ms
02-12 19:03:18.950  1884  1902 W libprocessgroup: kill(-22523, 9) failed: No such process
```

**Comment by christocracy** [comment]
[`FlutterBluePlugin.java`](https://github.com/pauldemarco/flutter_blue/blob/master/android/src/main/java/com/pauldemarco/flutterblue/FlutterBluePlugin.java#L94)

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.app.Activity.getSystemService(java.lang.String)' on a null object reference
02-12 19:03:18.874 22523 22523 E AndroidRuntime: 	at com.pauldemarco.flutterblue.FlutterBluePlugin.<init>(FlutterBluePlugin.java:94)
```

**Comment by mamen2022** [comment]
flutter --version
```
Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (3 months ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)
```

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    ✗ Android license status unknown.
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.31.0)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by christocracy** [comment]
`FlutterBluePlugin.java` needs to [do this](https://github.com/transistorsoft/flutter_background_fetch/blob/master/android/src/main/java/com/transistorsoft/flutter/backgroundfetch/BackgroundFetchPlugin.java#L46) to guard themselves against running headless.

**Comment by christocracy** [comment]
You should fork `FlutterBluePlugin` and issue them a PR.

**Comment by niravaecor** [comment]
@christocracy help needed 

I am also facing similar issue setting headless keeps stopping application. and cli stuck at waiting for port after installing sdk using **flutter run -v**.

Setting android:name=".Application" for Application class creates this issue, if i revert i works normally. also i have created Application.java with same content as documented. 

Also i have followed AndroidX migration for flutter. 

Thanks

**Comment by niravpatel2008** [comment]
@christocracy help needed 

I am also facing similar issue setting headless keeps stopping application. and cli stuck at waiting for port after installing sdk using **flutter run -v**.

Setting android:name=".Application" for Application class creates this issue, if i revert i works normally. also i have created Application.java with same content as documented. 

Also i have followed AndroidX migration for flutter. 

Thanks

**Comment by galves93** [comment]
I have the same problem, but i'm using barcode_scan. Have you know if this dependence can cause this problem? tks...

**Comment by christocracy** [comment]
You’ll see it in the stacktrace, the offending plugin will cause a NullPointerException accessing `registrar.activity()`

Plugins must always access the registrar.activity() during initialization, but in the Headless context, there is no Activity (that’s what headless means — the Activity of an Android application *IS* the head.
