### ISSUE TITLE
Issue with showing notification using Flutter Local Notifications package with Background-fetch package!!

### ISSUE THREAD

**Issue by hpatil879** [transistorsoft/flutter_background_fetch#138]
I want to run the background process after some time interval, The process checks for a particular time of day and then shows notification based on some logic. I am running this in release mode for verifying the background process on a real device. Packages used are [background-fetch](https://pub.dev/packages/background_fetch#-readme-tab-) and [flutter-local-notifications](https://pub.dev/packages/flutter_local_notifications)

The process is executed every 15 min, which is the minimum interval of the package background-fetch. But, whenever the background process is executed this is the error that is shown in the terminal.

**Terminal Logs**
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference, null)
E/flutter ( 2217): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569)
E/flutter ( 2217): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156)
E/flutter ( 2217): <asynchronous suspension>
E/flutter ( 2217): #2      FlutterLocalNotificationsPlugin.show (package:flutter_local_notifications/src/flutter_local_notifications_plugin.dart:134)
E/flutter ( 2217): <asynchronous suspension>
E/flutter ( 2217): #3      HeadstraitBanking.showScheduledTransfers (package:headstrait_digital_banking/main.dart:248)
E/flutter ( 2217): <asynchronous suspension>
E/flutter ( 2217): #4      checkScheduledTransfers (package:headstrait_digital_banking/main.dart:173)
E/flutter ( 2217): <asynchronous suspension>
E/flutter ( 2217): #5      _HeadstraitBankingState._onBackgroundFetch (package:headstrait_digital_banking/main.dart:486)
E/flutter ( 2217): <asynchronous suspension>
```

**main.dart**

 File
[demo.txt](https://github.com/hpatil879/demo/files/4813004/demo.txt)

Code
```dart
import "dart:async";
import "package:background_fetch/background_fetch.dart";
import "package:flutter/cupertino.dart";
import "package:flutter/material.dart";
import "package:flutter/services.dart";
import "package:flutter_local_notifications/flutter_local_notifications.dart";
import "package:provider/provider.dart";
import "package:rxdart/subjects.dart";
import "Screens/Home.dart";
import "providers/AppStateProvider.dart";

FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
    FlutterLocalNotificationsPlugin();

final BehaviorSubject<ReceivedNotification> didReceiveLocalNotificationSubject =
    BehaviorSubject<ReceivedNotification>();

final BehaviorSubject<String> selectNotificationSubject =
    BehaviorSubject<String>();

NotificationAppLaunchDetails notificationAppLaunchDetails;

class ReceivedNotification {
  ReceivedNotification({
    @required this.id,
    @required this.title,
    @required this.body,
    @required this.payload,
  });
  final int id;
  final String title;
  final String body;
  final String payload;
}

Future<void> backgroundFetchHeadlessTask(String taskId) async {
  if (taskId == "flutter_background_fetch") {
    await BackgroundFetch.scheduleTask(TaskConfig(
        taskId: "com.demo.fetch",
        delay: 5000,
        periodic: false,
        forceAlarmManager: true,
        stopOnTerminate: false,
        enableHeadless: true));
  }
  if (taskId == "com.demo.fetch") {
    await checkScheduledNotification();
  }
  BackgroundFetch.finish(taskId);
}

Future checkScheduledNotification() async {
  DateTime now = DateTime.now();
  if (now.hour == 16) {
    await showNotification("You have schedules for Today.");
  }
}

class MainClass extends StatelessWidget {
  const MainClass({Key key}) : super(key: key);
  @override
  Widget build(BuildContext context) => MultiProvider(
        providers: [
          ChangeNotifierProvider(create: (_) => AppStateProviders()),
        ],
        child: MaterialApp(
          home: DemoApp(),
        ),
      );
}

Future showNotification(String notificationMessage) async {
  var androidPlatformChannelSpecifics = AndroidNotificationDetails(
      "notification1", "notification", "scheduled for today.",
      importance: Importance.Max, priority: Priority.High);
  var iOSPlatformChannelSpecifics = IOSNotificationDetails();
  var platformChannelSpecifics = NotificationDetails(
      androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
  await flutterLocalNotificationsPlugin.show(
    0,
    "Test",
    notificationMessage,
    platformChannelSpecifics,
    payload: "Testing",
  );
}

class DemoApp extends StatefulWidget {
  const DemoApp({Key key}) : super(key: key);

  @override
  _DemoAppState createState() => _DemoAppState();
}

class _DemoAppState extends State<DemoApp> {
  final MethodChannel platform =
      MethodChannel("crossingthestreams.io/resourceResolver");

// 8888888888888 NOTIFICATIONS 888888888888888888888888888888888888888888888888
  Future setUpNotifications() async {
    WidgetsFlutterBinding.ensureInitialized();
    notificationAppLaunchDetails =
        await flutterLocalNotificationsPlugin.getNotificationAppLaunchDetails();
    var initializationSettingsAndroid =
        AndroidInitializationSettings("@mipmap/ic_launcher");
    var initializationSettingsIOS = IOSInitializationSettings(
        requestAlertPermission: false,
        requestBadgePermission: false,
        requestSoundPermission: false,
        onDidReceiveLocalNotification: (id, title, body, payload) async {
          didReceiveLocalNotificationSubject.add(ReceivedNotification(
              id: id, title: title, body: body, payload: payload));
        });
    var initializationSettings = InitializationSettings(
        initializationSettingsAndroid, initializationSettingsIOS);
    if (notificationAppLaunchDetails != null &&
        notificationAppLaunchDetails.didNotificationLaunchApp) {
      await flutterLocalNotificationsPlugin.initialize(initializationSettings,
          onSelectNotification: (payload) async {
        if (payload != null) {
          debugPrint("notification payload: $payload");
          selectNotificationSubject.add(payload);
        }
      });
    }
  }

  void _requestIOSPermissions() {
    flutterLocalNotificationsPlugin
        .resolvePlatformSpecificImplementation<
            IOSFlutterLocalNotificationsPlugin>()
        ?.requestPermissions(
          alert: true,
          badge: true,
          sound: true,
        );
  }

  void _configureDidReceiveLocalNotificationSubject() {
    didReceiveLocalNotificationSubject.stream
        .listen((ReceivedNotification receivedNotification) async {
      await showDialog(
        context: context,
        builder: (BuildContext context) => CupertinoAlertDialog(
          title: receivedNotification.title != null
              ? Text(receivedNotification.title)
              : null,
          content: receivedNotification.body != null
              ? Text(receivedNotification.body)
              : null,
          actions: [
            CupertinoDialogAction(
              isDefaultAction: true,
              child: Text("Ok"),
              onPressed: () async {
                Navigator.of(context, rootNavigator: true).pop();
                await Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => Screen2(),
                  ),
                );
              },
            )
          ],
        ),
      );
    });
  }

  void _configureSelectNotificationSubject() {
    selectNotificationSubject.stream.listen((payload) async {
      if (payload == "Testing") {
        await Navigator.push(
          context,
          MaterialPageRoute(builder: (context) => Screen2()),
        );
      }
    });
  }

  Future<void> applicationSetup() async {
    await setUpNotifications();
    _requestIOSPermissions();
    _configureDidReceiveLocalNotificationSubject();
    _configureSelectNotificationSubject();
    await BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
    await initPlatformState();
  }

  @override
  void initState() {
    super.initState();
    applicationSetup();
  }

  Future<void> initPlatformState() async {
    await BackgroundFetch.configure(
        BackgroundFetchConfig(
          minimumFetchInterval: 15,
          forceAlarmManager: false,
          stopOnTerminate: false,
          startOnBoot: true,
          enableHeadless: true,
          requiresBatteryNotLow: false,
          requiresCharging: false,
          requiresStorageNotLow: false,
          requiresDeviceIdle: false,
          requiredNetworkType: NetworkType.ANY,
        ),
        _onBackgroundFetch);
  }

  Future _onBackgroundFetch(String taskId) async {
    if (taskId == "flutter_background_fetch") {
      await BackgroundFetch.scheduleTask(TaskConfig(
          taskId: "com.demo.fetch",
          delay: 5000,
          periodic: false,
          forceAlarmManager: true,
          stopOnTerminate: false,
          enableHeadless: true));
    }
    if (taskId == "com.demo.fetch") {
      await checkScheduledNotification();
    }
    BackgroundFetch.finish(taskId);
  }

  @override
  void dispose() {
    didReceiveLocalNotificationSubject.close();
    selectNotificationSubject.close();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: Home(), routes: {
      "/home": (context) => Home(),
    });
  }
}
```

> To Forcefully run a background fetch I use below command in terminal

`adb shell cmd jobscheduler  shell c
run -f com.example.demo 999`

**Comment by christocracy** [comment]
Please create for me a simple *Hello World* app with your code above and share that Github repo with me.

**Comment by christocracy** [comment]
I successfully implement `flutter_local_notification` with `background_fetch` (including from Headless-task) by cloning the `flutter_local_notification` repo and modifying its `/example` as follows:

```diff
diff --git a/flutter_local_notifications/example/android/app/src/main/AndroidManifest.xml b/flutter_local_notifications/example/android/app/src/main/AndroidManifest.xml
index 482abd0..dc5fcde 100644
--- a/flutter_local_notifications/example/android/app/src/main/AndroidManifest.xml
+++ b/flutter_local_notifications/example/android/app/src/main/AndroidManifest.xml
@@ -1,4 +1,5 @@
 <manifest xmlns:android="http://schemas.android.com/apk/res/android"
+    xmlns:tools="http://schemas.android.com/tools"
     package="com.dexterous.flutterlocalnotificationsexample">

     <!-- The INTERNET permission is required for development. Specifically,
@@ -18,6 +19,7 @@
     <application
         android:name="io.flutter.app.FlutterApplication"
         android:label="flutter_local_notifications_example"
+        tools:replace="android:label"
         android:icon="@mipmap/ic_launcher">
         <activity
             android:name=".MainActivity"
diff --git a/flutter_local_notifications/example/android/build.gradle b/flutter_local_notifications/example/android/build.gradle
index 4e7ce9c..b427101 100644
--- a/flutter_local_notifications/example/android/build.gradle
+++ b/flutter_local_notifications/example/android/build.gradle
@@ -13,6 +13,10 @@ allprojects {
     repositories {
         google()
         jcenter()
+        maven {
+            // [required] background_fetch
+            url "${project(':background_fetch').projectDir}/libs"
+        }
     }
     gradle.projectsEvaluated {
         tasks.withType(JavaCompile) {
diff --git a/flutter_local_notifications/example/lib/main.dart b/flutter_local_notifications/example/lib/main.dart
index 9abe85c..36b5092 100644
--- a/flutter_local_notifications/example/lib/main.dart
+++ b/flutter_local_notifications/example/lib/main.dart
@@ -11,6 +11,15 @@ import 'package:http/http.dart' as http;
 import 'package:path_provider/path_provider.dart';
 import 'package:rxdart/subjects.dart';

+import 'package:background_fetch/background_fetch.dart';
+
+/// This "Headless Task" is run when app is terminated.
+void backgroundFetchHeadlessTask(String taskId) async {
+  print('[BackgroundFetch] Headless event received.');
+  await _showNotification();
+  BackgroundFetch.finish(taskId);
+}
+
 final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
     FlutterLocalNotificationsPlugin();

@@ -37,6 +46,18 @@ class ReceivedNotification {
   });
 }

+Future<void> _showNotification() async {
+  var androidPlatformChannelSpecifics = AndroidNotificationDetails(
+      'your channel id', 'your channel name', 'your channel description',
+      importance: Importance.Max, priority: Priority.High, ticker: 'ticker');
+  var iOSPlatformChannelSpecifics = IOSNotificationDetails();
+  var platformChannelSpecifics = NotificationDetails(
+      androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
+  await flutterLocalNotificationsPlugin.show(
+      0, 'plain title', 'plain body', platformChannelSpecifics,
+      payload: 'item x');
+}
+
 /// IMPORTANT: running the following code on its own won't work as there is setup required for each platform head project.
 /// Please download the complete example app from the GitHub repository where all the setup has been done
 Future<void> main() async {
@@ -72,6 +93,11 @@ Future<void> main() async {
       home: HomePage(),
     ),
   );
+
+  // Register to receive BackgroundFetch events after app is terminated.
+  // Requires {stopOnTerminate: false, enableHeadless: true}
+  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
+
 }

 class PaddedRaisedButton extends StatelessWidget {
@@ -103,11 +129,39 @@ class _HomePageState extends State<HomePage> {
   @override
   void initState() {
     super.initState();
+    _initBackgroundFetch();
     _requestIOSPermissions();
     _configureDidReceiveLocalNotificationSubject();
     _configureSelectNotificationSubject();
   }

+  void _initBackgroundFetch() {
+    // Configure BackgroundFetch.
+    BackgroundFetch.configure(BackgroundFetchConfig(
+        minimumFetchInterval: 15,
+        stopOnTerminate: false,
+        enableHeadless: true,
+        requiresBatteryNotLow: false,
+        requiresCharging: false,
+        requiresStorageNotLow: false,
+        requiresDeviceIdle: false,
+        requiredNetworkType: NetworkType.NONE
+    ), (String taskId) async {
+      // This is the fetch-event callback.
+      print("[BackgroundFetch] Event received $taskId");
+
+      await _showNotification();
+
+      // IMPORTANT:  You must signal completion of your task or the OS can punish your app
+      // for taking too long in the background.
+      BackgroundFetch.finish(taskId);
+    }).then((int status) {
+      print('[BackgroundFetch] configure success: $status');
+    }).catchError((e) {
+      print('[BackgroundFetch] configure ERROR: $e');
+    });
+
+  }
   void _requestIOSPermissions() {
     flutterLocalNotificationsPlugin
         .resolvePlatformSpecificImplementation<
@@ -438,17 +492,7 @@ class _HomePageState extends State<HomePage> {
     );
   }

-  Future<void> _showNotification() async {
-    var androidPlatformChannelSpecifics = AndroidNotificationDetails(
-        'your channel id', 'your channel name', 'your channel description',
-        importance: Importance.Max, priority: Priority.High, ticker: 'ticker');
-    var iOSPlatformChannelSpecifics = IOSNotificationDetails();
-    var platformChannelSpecifics = NotificationDetails(
-        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
-    await flutterLocalNotificationsPlugin.show(
-        0, 'plain title', 'plain body', platformChannelSpecifics,
-        payload: 'item x');
-  }
+

   Future<void> _showNotificationWithNoBody() async {
     var androidPlatformChannelSpecifics = AndroidNotificationDetails(
diff --git a/flutter_local_notifications/example/pubspec.yaml b/flutter_local_notifications/example/pubspec.yaml
index c1859c3..efa2c57 100644
--- a/flutter_local_notifications/example/pubspec.yaml
+++ b/flutter_local_notifications/example/pubspec.yaml
@@ -12,6 +12,7 @@ dependencies:
   rxdart: ^0.23.1
   flutter_local_notifications:
     path: ../
+  background_fetch: ^0.6.0

 dev_dependencies:
   flutter_driver:
```

**Comment by jvlichai** [comment]
how to get BuildContext within the headless method?  Because need navigation to a page from the notification clicks.

is that possible? like: 
`Future<void> backgroundFetchHeadlessTask(String taskId, BuidContext context) async {

    Future onSelectNotification(String payload) async {
      if (payload != null) {
        debugPrint('Notification payload: $payload');
      }
      await Navigator.push(context,
          new MaterialPageRoute(builder: (context) => new SecondRoute()));
    }

}`

**Comment by christocracy** [comment]
>Because need navigation to a page from the notification clicks

There is no navigation possible in the *Headless State* -- your app is not launched.  

If the user clicks the notification in this state, the Android OS will *cause* your app to be re-launched.

**Comment by AlaaEldeenYsr** [comment]
@christocracy 
And how you can open the app in a forced way in the headless task? I tried to use device_apps package but it's not working

**Comment by christocracy** [comment]
>And how you can open the app in a forced way in the headless task?

Don't even try.  *Android 10* now [forbids this](https://developer.android.com/guide/components/activities/background-starts)

**Comment by AlaaEldeenYsr** [comment]
Oh, Thank you @christocracy

**Comment by banderberg** [comment]
@christocracy Have you tried your modified example with zonedSchedule from the local notification plugin?  I can schedule notifications after my app loads and I close it to enter headless mode, but **after I restart the app**, triggering a headless event with jobscheduler while running logcat shows that the headless event is received, but no notifications ever show up.
