### ISSUE TITLE
error while executing job

### ISSUE THREAD

**Issue by minh98** [transistorsoft/flutter_background_fetch#14]
app crash and logcat
```
2019-02-27 13:12:37.249 11513-11513/? D/TSBackgroundFetch: - Background Fetch event received
2019-02-27 13:12:37.253 11513-11513/? D/TSBackgroundFetch: - finish
2019-02-27 13:12:37.253 11513-11513/? D/TSBackgroundFetch: - jobFinished
2019-02-27 13:12:37.259 11513-11513/? D/TSBackgroundFetch: HeadlessJobService onStartJob
2019-02-27 13:12:37.260 11513-11513/? D/TSBackgroundFetch: 💀 [HeadlessTask]
2019-02-27 13:12:37.345 11513-11513/? E/JobServiceEngine: Error while executing job: 998
2019-02-27 13:12:37.345 11513-11513/? D/AndroidRuntime: Shutting down VM
2019-02-27 13:12:37.347 11513-11513/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tbm.test_background_fetch, PID: 11513
    java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.PluginRegistry$PluginRegistrantCallback.registerWith(io.flutter.plugin.common.PluginRegistry)' on a null object reference
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:112)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.PluginRegistry$PluginRegistrantCallback.registerWith(io.flutter.plugin.common.PluginRegistry)' on a null object reference
        at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.initFlutterView(HeadlessTask.java:133)
        at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.<init>(HeadlessTask.java:47)
        at com.transistorsoft.flutter.backgroundfetch.HeadlessJobService.onStartJob(HeadlessJobService.java:38)
        at android.app.job.JobService$1.onStartJob(JobService.java:71)
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
2019-02-27 13:12:37.351 1697-1712/? I/ActivityManager: Showing crash dialog for package com.tbm.test_background_fetch u0
```

**Comment by christocracy** [comment]
I've created a new bug report template.  Please edit your post and provide the following information.

**Your Environment**
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter doctor`):
* Plugin config

**To Reproduce**
Steps to reproduce the behavior:
1. 
2.
3.
4.

**Debug logs**
- ios XCode logs, 
- use #getLog #emailLog methods (@see docs)
- Android: $ adb logcat

**Additional context**
Add any other context about the problem here.

**Comment by christocracy** [comment]
Closed for lack of feedback.
