### ISSUE TITLE
[BUG] iOS = The example project not working

### ISSUE THREAD

**Issue by rrifafauzikomara** [transistorsoft/flutter_background_fetch#146]
**Your Environment**
* Plugin version: I just clone the repository
* Platform: iOS
* Device detail: Simulator iPhone 11 Pro Max (Version 11.6 (921.9.1), SimulatorKit 581.9.1, CoreSimulator 704.12.2)
* Flutter info (`flutter info`, `flutter doctor`):
```
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G2021, locale en-US)
    • Flutter version 1.20.1 at /Users/rrifafauzikomara/Documents/flutter
    • Framework revision 2ae34518b8 (3 weeks ago), 2020-08-05 19:53:19 -0700
    • Engine revision c8e3b94853
    • Dart version 2.9.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/rrifafauzikomara/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Android SDK built for x86 (mobile) • emulator-5554
      • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11 Pro Max (mobile)         • FDF80209-3C4A-417F-BC21-3A9EA2B4FDCE
      • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)

! Doctor found issues in 1 category.
```

**Debug logs**
```
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Warning: Podfile is out of date
  This can cause issues if your application depends on plugins that do not support iOS.
  See https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms for details.
  If you have local Podfile edits you would like to keep, see https://github.com/flutter/flutter/issues/45197 for instructions.
To regenerate the Podfile, run:
  rm ios/Podfile

Running Xcode build...
Xcode build done.                                           13.4s
[TSBackgroundFetch load]: (
)
[TSBGAppRefreshSubscriber load]: {
    "flutter_background_fetch" = "<TSBGAppRefreshSubscriber identifier=flutter_background_fetch, executed=0, enabled=1>";
}
[TSBackgroundFetch registerForTaskWithIdentifier: com.transistorsoft.customtask
Waiting for iPhone 11 Pro Max to report its views...
Debug service listening on ws://127.0.0.1:59035/_iZXpy06QjM=/ws
Syncing files to device iPhone 11 Pro Max...
[TSBackgroundFetch scheduleBGAppRefresh] com.transistorsoft.fetch
[TSBackgroundFetch scheduleProcessingTask] <TSBGTask identifier=com.transistorsoft.customtask, delay=10, periodic=0 enabled=0>
[TSBackgroundFetch scheduleTask] ERROR:  Failed to submit task request: Error Domain=BGTaskSchedulerErrorDomain Code=1 "(null)"
flutter: [BackgroundFetch] configure success: 2
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: PlatformException(1, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
#3      BackgroundFetch.scheduleTask (package:background_fetch/background_fetch.dart:475:33)
#4      _MyAppState.initPlatformState (package:background_fetch_example/main.dart:110:21)
#5      _rootRunUnary (dart:async/zone.dart:1198:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#11<…>
```

**Additional context**
When I running on iOS simulator using my Android Studio, show the above log and the apps only show the widget with cons "EMPTY_TEXT". But when I running on the Android emulator, the example project is working.

**Comment by christocracy** [comment]
The new iOS `BGTaskScheduler` doesn't work in Simulator.  Try on *real* device.
