### ISSUE TITLE
[BUG] Unable to manually generate background event in iOS

### ISSUE THREAD

**Issue by ydotmalik** [transistorsoft/flutter_background_fetch#153]
**Your Environment**
* Plugin version: 0.6.0
* Platform: iOS
* OS version: iOS 13.5
* Device manufacturer / model: iOS simulator for iPhone 11 Pro Max
* Flutter info (`flutter info`, `flutter doctor`):
```
% flutter doctor -v
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.4 19E2269, locale en-US)
    • Flutter version 1.20.2 at /Users/ymalik/dev/flutter
    • Framework revision bbfbf1770c (5 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/ymalik/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • 9ED88F0B-965E-4CD2-A1FD-AAC65236EADF • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-5 (simulator)

• No issues found!
```

* Plugin config
Default code in main.dart in background_fetch example

**To Reproduce**
1. Use example at https://github.com/transistorsoft/flutter_background_fetch/tree/master/example
2. Toggle switch at top right hand corner
3. Observe below error

**Debug logs**
```
[TSBackgroundFetch start] (null)
[TSBackgroundFetch scheduleBGAppRefresh] com.transistorsoft.fetch
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: Invalid argument(s) (error): Must not be null
#0      ArgumentError.checkNotNull (dart:core/errors.dart:194:27)
#1      _Completer.completeError (dart:async/future_impl.dart:21:19)
#2      BackgroundFetch.start.<anonymous closure> (package:background_fetch/background_fetch.dart:402:17)
#3      _rootRunUnary (dart:async/zone.dart:1198:47)
#4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#5      _FutureListener.handleError (dart:async/future_impl.dart:160:20)
#6      Future._propagateToListeners.handleError (dart:async/future_impl.dart:708:47)
#7      Future._propagateToListeners (dart:async/future_impl.dart:729:24)
#8      Future._completeError (dart:async/future_impl.dart:537:5)
#9      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:47:15)
#10     MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart)
<asynchronous suspension>
#11     MethodChannel.invokeMethod (package:flutter/src/servi<…>
```

**Additional context**
I do not observe this problem on Android; toggling switch results in background fetch event being generated.

**Comment by christocracy** [comment]
The new BackgroundFetch API doesn't work in iOS Simulator.  Try it on real device.

**Comment by ydotmalik** [comment]
I able to simulate the background fetch event from Xcode (Debug->Simulate background fetch), which is good enough for me.

**Comment by christocracy** [comment]
I see the problem here running in the simulator.  This error will be properly handled in the next release `0.7.0`, due soon.
