### ISSUE TITLE
[BUG] java.lang.IllegalArgumentException: No such service 

### ISSUE THREAD

**Issue by javawolfpack** [transistorsoft/flutter_background_fetch#16]
**Your Environment**
* Plugin version: 33.3.1
* Platform: Android
* OS version: 9
* Device manufacturer / model: Pixel 3 XL
* Flutter info (`flutter info`, `flutter doctor`):
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.0.0 at /Users/bryandixon/development/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/bryandixon/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • Pixel 3 XL • 89AY04YTA • android-arm64 • Android 9 (API 28)

• No issues found!
```

* Plugin config

**To Reproduce**
```dart
1. Future<void> initPlatformState() async {
    BackgroundFetch.configure(BackgroundFetchConfig(
        minimumFetchInterval: 15,
        stopOnTerminate: false,
        enableHeadless: true
    ), () async {
      _fetchData(); //my async method that I want to run periodically in the background
      BackgroundFetch.finish();
    });
  }
2. Started App
3. Seems like it can't find the merged service definition in the Android Manifest
```

**Debug logs**
```
Syncing files to device Pixel 3 XL...
D/TSBackgroundFetch(17880): - configure: {
D/TSBackgroundFetch(17880):   "minimumFetchInterval": 15,
D/TSBackgroundFetch(17880):   "stopOnTerminate": false,
D/TSBackgroundFetch(17880):   "startOnBoot": false,
D/TSBackgroundFetch(17880):   "forceReload": false,
D/TSBackgroundFetch(17880):   "jobService": "com.transistorsoft.flutter.backgroundfetch.HeadlessJobService"
D/TSBackgroundFetch(17880): }
D/TSBackgroundFetch(17880): - start
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): Failed to handle method call
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): java.lang.IllegalArgumentException: No such service ComponentInfo{com.example.myapp/com.transistorsoft.tsbackgroundfetch.FetchJobService}
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): 	at android.os.Parcel.createException(Parcel.java:1954)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): 	at android.os.Parcel.readException(Parcel.java:1918)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): 	at android.os.Parcel.readException(Parcel.java:1868)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): 	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:184)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): 	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:44)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): 	at com.transistorsoft.tsbackgroundfetch.BackgroundFetch.start(BackgroundFetch.java:95)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): 	at com.transistorsoft.tsbackgroundfetch.BackgroundFetch.configure(BackgroundFetch.java:67)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): 	at com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin.configure(BackgroundFetchPlugin.java:119)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): 	at com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin.onMethodCall(BackgroundFetchPlugin.java:63)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): Caused by: android.os.RemoteException: Remote stack trace:
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): 	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:2494)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): 	at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2556)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): 	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:60)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): 	at android.os.Binder.execTransact(Binder.java:731)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(17880): 
```

**Additional context**
Seems similar to issue: https://github.com/transistorsoft/flutter_background_fetch/issues/13
I've tried version 0.1.2 (solution for issue #13), '^0.1.0', and the pull requested version for AndroidX and all of them give the above error.

**Comment by christocracy** [comment]
- I just created a new app `flutter create fetch`

```
ford:fetch020 chris$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (2 available)
```

- Installed latest `background_fetch: ^0.2.0`
- No problems here.

Are you sure you're using the right version of Flutter?
- You:  `Flutter (Channel stable, v1.0.0`
- Me:  `Flutter (Channel stable, v1.2.1`

**Comment by javawolfpack** [comment]
@christocracy I didn't realize a newer stable channel update had come out, that's good to know so have now upgraded. Still getting the error... curious if its something I'm missing with the in install/configuration to get your plugin working. 

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.2.1 at /Users/bryandixon/development/flutter
    • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/bryandixon/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • Pixel 3 XL • 89AY04YTA • android-arm64 • Android 9 (API 28)

• No issues found!
```
Switched to latest background_fetch: ^0.2.0

My android manifest:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.example.myapp">

    <application
        tools:replace="android:label"
        android:name=".Application"
        android:label="myapp"
        android:icon="@mipmap/ic_launcher">
<activity
        android:name=".Application"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
```
Application.kt:
```
package com.example.myapp

import com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin;
import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugins.GeneratedPluginRegistrant

class Application : FlutterApplication(), PluginRegistry.PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate();
        BackgroundFetchPlugin.setPluginRegistrant(this);
    }

    override fun registerWith(registry: PluginRegistry) {
        GeneratedPluginRegistrant.registerWith(registry);
    }
}
```
Still getting the same error:
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): Failed to handle method call
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): java.lang.IllegalArgumentException: No such service ComponentInfo{com.example.myapp/com.transistorsoft.tsbackgroundfetch.FetchJobService}
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 	at android.os.Parcel.createException(Parcel.java:1954)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 	at android.os.Parcel.readException(Parcel.java:1918)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 	at android.os.Parcel.readException(Parcel.java:1868)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:184)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:44)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 	at com.transistorsoft.tsbackgroundfetch.BackgroundFetch.start(BackgroundFetch.java:95)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 	at com.transistorsoft.tsbackgroundfetch.BackgroundFetch.configure(BackgroundFetch.java:67)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 	at com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin.configure(BackgroundFetchPlugin.java:121)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 	at com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin.onMethodCall(BackgroundFetchPlugin.java:65)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): Caused by: android.os.RemoteException: Remote stack trace:
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 	at com.android.server.job.JobSchedulerService$JobSchedulerStub.enforceValidJobRequest(JobSchedulerService.java:2494)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 	at com.android.server.job.JobSchedulerService$JobSchedulerStub.schedule(JobSchedulerService.java:2556)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 	at android.app.job.IJobScheduler$Stub.onTransact(IJobScheduler.java:60)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 	at android.os.Binder.execTransact(Binder.java:731)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(14363): 
I

**Comment by christocracy** [comment]
Have you tried booting the `/example` app in this repo?

**Comment by javawolfpack** [comment]
Example worked... I recreated my whole project without Kotlin support, and it now runs without the exception. I put some debug output in the callback... and it is showing up every 15 minutes so appears to be working. 

But the only real difference I could see between my original app and your example is the Kotlin support.

**Comment by christocracy** [comment]
I have no experience with Kotlin.  Are you actually writing Kotlin code?

**Comment by javawolfpack** [comment]
No... it was just a checkbox in Android studio when creating a new flutter project. I haven't taught mobile in 2 years, and it was either learn Kotlin and teach native Android this semester or pick up Flutter and teach that. I opted for Dart/Flutter. Trying to limit the need to write native code in my usage and teaching of Flutter, hence my interest in this project as a way to run background periodic services.

**Comment by christocracy** [comment]
I would stick to standard Java / Obj-c in Flutter.  Introducing Swift/Kotlin adds another layer of things to go wrong.

**Comment by Samaritan1011001** [comment]
@christocracy , Thank you for the plugin. But, I am seeing the same error message with the `Java` implementation as well: 
```
W/TSBackgroundFetch(18222): - Configuration error:  {forceReload: false, jobService: null} is incompatible with stopOnTerminate: false:  Enforcing stopOnTerminate: true.
D/TSBackgroundFetch(18222): - configure: {
D/TSBackgroundFetch(18222):   "minimumFetchInterval": 15,
D/TSBackgroundFetch(18222):   "stopOnTerminate": true,
D/TSBackgroundFetch(18222):   "startOnBoot": false,
D/TSBackgroundFetch(18222):   "forceReload": false
D/TSBackgroundFetch(18222): }
D/TSBackgroundFetch(18222): - start
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(18222): Failed to handle method call
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(18222): java.lang.IllegalArgumentException: No such service ComponentInfo{com.comapny.app.v3/com.transistorsoft.tsbackgroundfetch.FetchJobService}
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(18222): 	at android.os.Parcel.readException(Parcel.java:1687)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(18222): 	at android.os.Parcel.readException(Parcel.java:1636)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(18222): 	at android.app.job.IJobScheduler$Stub$Proxy.schedule(IJobScheduler.java:158)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(18222): 	at android.app.JobSchedulerImpl.schedule(JobSchedulerImpl.java:42)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(18222): 	at com.transistorsoft.tsbackgroundfetch.BackgroundFetch.start(BackgroundFetch.java:95)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(18222): 	at com.transistorsoft.tsbackgroundfetch.BackgroundFetch.configure(BackgroundFetch.java:67)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(18222): 	at com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin.configure(BackgroundFetchPlugin.java:121)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(18222): 	at com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin.onMethodCall(BackgroundFetchPlugin.java:65)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(18222): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(18222): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(18222): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(18222): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(18222): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(18222): 	at android.app.ActivityThread.main(ActivityThread.java:6123)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(18222): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(18222): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(18222): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

```
 `enableHeadless` is set to `false`. 

When I set it to `true` and follow the setup guide [here](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md#headless-mechanism-with-enableheadless-true), my app crashes and the logcat shows this: 
```
E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application com.company.app.v3.Application: java.lang.ClassNotFoundException: Didn't find class "com.company.app.v3.Application" on path: DexPathList[[zip file "/data/app/com.company.app.v3-1/base.apk"],nativeLibraryDirectories=[/data/app/com.company.app.v3-1/lib/arm, /data/app/com.company.app.v3-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
03-20 13:59:12.014 17609 17609 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:802)
03-20 13:59:12.014 17609 17609 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5376)
03-20 13:59:12.014 17609 17609 E AndroidRuntime: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
03-20 13:59:12.014 17609 17609 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1541)
03-20 13:59:12.014 17609 17609 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-20 13:59:12.014 17609 17609 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
03-20 13:59:12.014 17609 17609 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6123)
03-20 13:59:12.014 17609 17609 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-20 13:59:12.014 17609 17609 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
03-20 13:59:12.014 17609 17609 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
```

My `Application.java` : 
```
import com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class Application extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {
    @Override
    public void onCreate() {
        super.onCreate();
        BackgroundFetchPlugin.setPluginRegistrant(this);
    }

    @Override
    public void registerWith(PluginRegistry registry) {
        GeneratedPluginRegistrant.registerWith(registry);
    }
}
```

AndroidManifest.xml:
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          xmlns:tools="http://schemas.android.com/tools"
          package="com.company.app.v3">

    <!-- The INTERNET permission is required for development. Specifically,
         flutter needs it to communicate with the running application
         to allow setting breakpoints, to provide hot reload, etc.
    -->
    <uses-permission android:name="android.permission.INTERNET"/>

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application

            android:label="App"
            android:name=".Application"
            tools:node="replace"
            android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
</manifest>

```

**Comment by christocracy** [comment]
- Plugin version
- Platform: Android
- OS version: 
- Device manufacturer / model:
- Flutter info (flutter info, flutter doctor):

**Comment by Samaritan1011001** [comment]
@christocracy here it is,
Plugin version : `^0.1.0`
Platform: Android
OS version: Android version 7.0
Device manufacturer / model: Moto G4 Plus
Flutter info (flutter info, flutter doctor): 
```
[✓] Flutter (Channel unknown, v1.0.0, on Mac OS X 10.14 18A391, locale en-IN)
    • Flutter version 1.0.0 at /Users/manojn/Documents/flutter
    • Framework revision 5391447fae (4 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/manojn/Library/Android/sdk
    • Android NDK at /Users/manojn/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/manojn/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ✗ Android license status unknown.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5901

[✓] Connected device (1 available)
    • Moto G 4 • ZY223V5ZKJ • android-arm • Android 7.0 (API 24)

! Doctor found issues in 1 category.

```

**Comment by Samaritan1011001** [comment]
The same app with the plugin works well on my IOS devices. I suspect it's the configuration on android but I have followed and done everything as it is shown [here](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md)

**Comment by christocracy** [comment]
And what about Kotlin support?  Did you enable that?

**Comment by Samaritan1011001** [comment]
I haven't used Kotlin here so I did not enable any support. My project uses Java for android. Do I still need to enable Kotlin support?

**Comment by christocracy** [comment]
@Samaritan1011001 No.  I asked that because it was [the solution above](https://github.com/transistorsoft/flutter_background_fetch/issues/16#issuecomment-473415546).  You *are* reading this *entire* thread, *right*?

**Comment by christocracy** [comment]
@Samaritan1011001 did you compare the results of *your* `flutter doctor` [with mine](https://github.com/transistorsoft/flutter_background_fetch/issues/16#issuecomment-473325158)

**Comment by Samaritan1011001** [comment]
@christocracy  Yes I did read that. But I had never enabled Kotlin support to begin with unless it's by default when creating the project it does not make sense right? 
All the files in my `android/src/main` directory is in Java and they are the defaults.

**Comment by joserocha3** [comment]
@Samaritan1011001 try adding `package com.company.app.v3;` (or whatever you bundle ID is) to the top of `Application.java`.

```java
package com.company.app.v3;

import com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin;
import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class Application extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {
    @Override
    public void onCreate() {
        super.onCreate();
        BackgroundFetchPlugin.setPluginRegistrant(this);
    }

    @Override
    public void registerWith(PluginRegistry registry) {
        GeneratedPluginRegistrant.registerWith(registry);
    }
}
```

**Comment by christocracy** [comment]
@Samaritan1011001 I see.  So people are just copy/pasting the `Application.java` from the README!

My assumption is people would do this *then* copy the contents from `README`:
![](https://dl.dropboxusercontent.com/s/88etw5tjjuspkem/Screenshot%202019-03-22%2009.52.40.png?dl=1)
![](https://dl.dropboxusercontent.com/s/xch3ja3dzjf6717/Screenshot%202019-03-22%2009.54.22.png?dl=1)

The instructions will need to be made more explicit.

**Comment by christocracy** [comment]
```diff
package com.company.app.v3;

+import com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin;
+import io.flutter.app.FlutterApplication;
+import io.flutter.plugin.common.PluginRegistry;
+import io.flutter.plugins.GeneratedPluginRegistrant;

+public class Application extends FlutterApplication implements +PluginRegistry.PluginRegistrantCallback {
+    @Override
+    public void onCreate() {
+        super.onCreate();
+        BackgroundFetchPlugin.setPluginRegistrant(this);
+    }

+    @Override
+    public void registerWith(PluginRegistry registry) {
+        GeneratedPluginRegistrant.registerWith(registry);
+    }
+}
```

**Comment by joserocha3** [comment]
@christocracy I can't speak for everyone, but I use VS code. There is no class builder in VS code that would add the package to the top of the file for me.

**Comment by Samaritan1011001** [comment]
@joserocha3 Thank you so much for pointing it out. It's works like a charm now. 
@christocracy Yes indeed. That's what I usually do but for some reason create a `Java file` did not show up and I am not that good with java/obj c code and hence this state. 
<img width="573" alt="Screenshot 2019-03-22 at 7 29 15 PM" src="https://user-images.githubusercontent.com/10944487/54827935-1c6c8900-4cd9-11e9-8e73-99319b344fe9.png">

**Comment by christocracy** [comment]
The best way to operate upon the Android-specific app is to open it as a separate Android Studio project:

Open `your_app/android`

If I comment out my `package` at top-of-file, Android Studio warns me of the error:
![](https://dl.dropboxusercontent.com/s/2pzqcae8bt4sv22/Screenshot%202019-03-22%2010.05.07.png?dl=1)

**Comment by anantaramdas** [comment]
@christocracy Could you please help me:
I'm getting same issue while adding your library into my existing application. While fresh app is working perfectly here I'm getting same error as above:
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
W/TSBackgroundFetch(12212): - Configuration error:  {forceReload: false, jobService: null} is incompatible with stopOnTerminate: false:  Enforcing stopOnTerminate: true.
D/TSBackgroundFetch(12212): - configure: {
D/TSBackgroundFetch(12212):   "minimumFetchInterval": 15,
D/TSBackgroundFetch(12212):   "stopOnTerminate": true,
D/TSBackgroundFetch(12212):   "requiredNetworkType": 0,
D/TSBackgroundFetch(12212):   "requiresBatteryNotLow": false,
D/TSBackgroundFetch(12212):   "requiresCharging": false,
D/TSBackgroundFetch(12212):   "requiresDeviceIdle": false,
D/TSBackgroundFetch(12212):   "requiresStorageNotLow": false,
D/TSBackgroundFetch(12212):   "startOnBoot": false,
D/TSBackgroundFetch(12212):   "forceReload": false
D/TSBackgroundFetch(12212): }
D/TSBackgroundFetch(12212): - start
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(12212): Failed to handle method call
E/MethodChannel#com.transistorsoft/flutter_background_fetch/methods(12212): java.lang.IllegalArgumentException: No such service ComponentInfo{com.example.mobile/com.transistorsoft.tsbackgroundfetch.FetchJobService}
```

I rereads Android setup section of your manual and did everything as you instructed. I have package name in my Application.kt file:
![image](https://user-images.githubusercontent.com/7561827/68615569-fdbb3c80-04cb-11ea-904b-cd443ce48527.png)

Could you please point me what is wrong.

Flutter doctor is:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.15.1 19B88, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
[✓] VS Code (version 1.40.0)
[✓] Connected device (1 available)
```

Thank you in advance!

**Comment by christocracy** [comment]
Have you opened your /android app separately in Android Studio?
