### ISSUE TITLE
[BUG] Background crash on 0.6.0

### ISSUE THREAD

**Issue by MooNag** [transistorsoft/flutter_background_fetch#172]
**Your Environment**
* Plugin version: 0.6.0
* Platform: Android
* OS version: 8, 9, 10, 11
* Device manufacturer / model: (many from Google, Oneplus, samsung, LG...)
* Flutter info (`flutter info`, `flutter doctor`):

<details>
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.19041.630], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.51.1)
[√] Connected device (4 available)
```
</details>

* Plugin config

<details>

  dio: 3.0.10
  intl: 0.16.1
  flutter_svg: 0.19.1
  fluttertoast: 4.0.1 
  shared_preferences: 0.5.12+4
  geolocator: 6.1.6
  geocoding: 1.0.5
  permission_handler: 4.4.0+hotfix.4 
  connectivity: 2.0.1
  url_launcher: 5.7.10
  background_fetch: 0.6.0
  device_calendar: 3.1.0
  share: 0.6.5+4
  carousel_slider: 2.3.1
  in_app_update: 1.1.14
  path_provider: 1.6.24

  sticky_headers: 0.1.8+1

  flutter_map: 0.10.1+1
  flutter_map_marker_cluster: 0.3.1

  package_info: 0.4.3+2
  flutter_local_notifications: 3.0.1+2
  flutter_compass: 0.5.0
  in_app_purchase: 0.3.4+16
  launch_review: 2.0.0
  flutter_device_locale: 0.4.0

  firebase_admob: 0.10.2
  admob_flutter: 1.0.1
  app_tracking_transparency: 1.0.1+1

  firebase_core: 0.5.2
  firebase_analytics: 6.2.0
  firebase_performance: 0.4.2
  firebase_crashlytics: 0.2.3
  firebase_remote_config: 0.4.2
  firebase_messaging: 8.0.0-dev.8

</details>

**To Reproduce**
1. Background tasks fail. 

**Debug logs**
- ios XCode logs, 
- Android: `$ adb logcat`

Stack trace:

```
Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.embedding.engine.loader.FlutterApplicationInfo.flutterAssetsDir' on a null object reference
       at io.flutter.embedding.engine.loader.FlutterLoader.findAppBundlePath(FlutterLoader.java:2)
       at io.flutter.view.FlutterMain.findAppBundlePath(FlutterMain.java:8)
       at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.startBackgroundIsolate(HeadlessTask.java:12)
       at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.dispatch(HeadlessTask.java:4)
       at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.run(HeadlessTask.java)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7656)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Additional context**

I am using the android V2 embedding.
It looks like the firebase_messaging: 8.0.0-dev.X plugin versions are casuing issues? It crashes on 8, 5, and 2. 
I am not entirely sure. As the stack trace is from THIS plugin crashing. Just wanted to add it as context.

*Configure code:*
<details>

Configure code:
```
BackgroundFetch.configure(BackgroundFetchConfig(
      minimumFetchInterval: 10,
      stopOnTerminate: false,
      enableHeadless: true,
      forceAlarmManager: true,
      startOnBoot: true,
      requiresBatteryNotLow: false,
      requiresCharging: false,
      requiresStorageNotLow: false,
      requiresDeviceIdle: false,
      requiredNetworkType: NetworkType.NONE,
    ), backgroundFetchHeadlessTask);
```

backgroundFetchHeadlessTask:

```

/// This "Headless Task" is run when app is terminated.
Future<void> backgroundFetchHeadlessTask(String taskId) async {

  // This is the fetch-event callback.
  print("[BackgroundFetch] taskId: $taskId");

  await NotificationManager.doNotifications(true);

  // Finish, providing received taskId.
  BackgroundFetch.finish(taskId);
}

```

</details>

**android/build.grade**

<details>

```
buildscript {

    //For background_fetch plugin.
    ext.kotlin_version = '1.3.0' // Must use 1.3.0 or higher.
    ext {
        compileSdkVersion   = 29                // or higher
        targetSdkVersion    = 29                // or higher
        appCompatVersion    = "1.0.2"           // or higher
    }

    repositories {
        google()
        jcenter()
        maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }


    }

    dependencies {
        //classpath 'com.android.tools.build:gradle:3.2.1'
        //classpath 'com.android.tools.build:gradle:3.4.0'
        classpath 'com.android.tools.build:gradle:3.5.0'

        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'
        //classpath 'io.fabric.tools:gradle:1.31.2'

        //classpath 'com.google.gms:google-services:4.0.1'
        classpath 'com.google.gms:google-services:4.3.3'

    }

}


allprojects {
    repositories {
        google()
        jcenter()

        maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }

    }
}


rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}


```

</details>

**app/build.gradle**

<details>

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"


def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}


android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        applicationId "REMOVED"
        minSdkVersion 16
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release

            minifyEnabled true
            useProguard false 

            shrinkResources false

            multiDexEnabled true

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'


        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    implementation 'androidx.test:runner:1.1.1'
    implementation 'androidx.test.espresso:espresso-core:3.1.1'

}

apply plugin: 'com.google.firebase.crashlytics'

apply plugin: 'com.google.gms.google-services'
//apply plugin: 'com.google.firebase.firebase-perf'

//com.google.gms.googleservices.GoogleServicesPlugin.config.disableVersionCheck = true
```

</details>

**Android Manifest**
<details>

```

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="REMOVED APP ID"
    xmlns:tools="http://schemas.android.com/tools">

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->

    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />  <!-- FOR ADS-->

    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />

    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.VIBRATE" />
    <uses-permission android:name="android.permission.READ_CALENDAR" />
    <uses-permission android:name="com.android.vending.BILLING" />

    <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />

    <!-- DO NOT INCLUDE THIS UNLESS ABSOLUTELY NECESSCARY -->
    <uses-permission android:name="android.permission.WRITE_CALENDAR" />


    <application
        tools:replace="android:label"
        android:label="REMOVED APP NAME"
        android:icon="@mipmap/ic_launcher">

        <!--  I am using a custom main activity so I can send platform channel messages. -->
        <!--  android:name  was android:name="io.flutter.embedding.android.FlutterActivity" -->
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">


            <!-- Specify that the launch screen should continue being displayed -->
            <!-- until Flutter renders its first frame. -->
            <meta-data
                android:name="io.flutter.embedding.android.SplashScreenDrawable"
                android:resource="@drawable/launch_background" />

            <!-- Theme to apply as soon as Flutter begins rendering frames -->
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/LaunchTheme"
                />


            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

        </activity>

        <meta-data android:name="com.google.android.gms.version"
            android:value="@integer/google_play_services_version" />

        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />


        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="REMOVED"/>
        

        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"></action>
            </intent-filter>
        </receiver>
        <receiver android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver" />


        <!--Widget stuff-->
                REMOVED AS NOT RELEVANT


    </application>

</manifest>


```

</details>

**Custom MainActivity.java**

<details>
```
     package com.app.id REMOVED;

     import io.flutter.embedding.android.FlutterActivity;
     import io.flutter.embedding.engine.FlutterEngine;
     import android.widget.Toast;
     import androidx.annotation.NonNull;

     import io.flutter.plugin.common.MethodCall;
     import io.flutter.plugin.common.MethodChannel;
     import io.flutter.plugin.common.MethodChannel.MethodCallHandler;
     import android.os.Bundle;
     import android.content.Intent;
     import android.content.IntentFilter;

     import android.appwidget.AppWidgetManager;

     //Extra immports for testing
     import android.content.ContextWrapper;
     import android.os.BatteryManager;
     import android.os.Build.VERSION;
     import android.os.Build.VERSION_CODES;

     import android.app.NotificationManager;
     import android.app.NotificationChannel;
     import android.os.Build;

    public class MainActivity extends FlutterActivity {


    @Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        super.configureFlutterEngine(flutterEngine);

        // Create the NotificationChannel, but only on API 26+ because
        // the NotificationChannel class is new and not in the support library
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            FUNCTIONS REMOVED ();
            FUNCTIONS REMOVED ();
            FUNCTIONS REMOVED ();
            FUNCTIONS REMOVED ();
            FUNCTIONS REMOVED ();
            FUNCTIONS REMOVED ();
        }

    }

   FUNCTIONS REMOVED TO SETUP NOTIFICATION CHANNELS.
   THIS NEVER HAD ISSUES WITH CRASHES.


}
```

</details>

**Comment by MooNag** [comment]
It appears that adding

```
        android:name="io.flutter.app.FlutterApplication"
```

To the application tag in the androidmanifest fixes the crashing issue on my emulator. This might be helpful for finding the solution.
