### ISSUE TITLE
[BUG] Unfortunately app stopped 

### ISSUE THREAD

**Issue by ziasultan2** [transistorsoft/flutter_background_fetch#18]
There is no error shows. But when launched app It shows app has been stopped unfortunately.
Please have a look on these images
![Screenshot_1](https://user-images.githubusercontent.com/10562120/54658409-7b72a800-4af7-11e9-81cf-b60062f144a1.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/10562120/54658410-7b72a800-4af7-11e9-9a01-b6f4c074d0da.jpg)

**Comment by christocracy** [comment]
Why are you not providing the stacktrace from `$ adb logcat`?

**Comment by christocracy** [comment]
And why have you ignored the issue template?

**Comment by christocracy** [comment]
Closing until you provide the request information in the issue template.

**Comment by ziasultan2** [comment]
Here is the logcat of crush. 
--------- beginning of crash
03-20 11:12:51.287 3542-3542/com.ziasultan.ip_tracker E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ziasultan.ip_tracker, PID: 3542
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.ziasultan.ip_tracker/com.ziasultan.ip_tracker.Application}: java.lang.ClassCastException: com.ziasultan.ip_tracker.Application cannot be cast to android.app.Activity
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2238)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
        at android.app.ActivityThread.access$800(ActivityThread.java:153)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5293)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.ClassCastException: com.ziasultan.ip_tracker.Application cannot be cast to android.app.Activity
        at android.app.Instrumentation.newActivity(Instrumentation.java:1066)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2228)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392) 
        at android.app.ActivityThread.access$800(ActivityThread.java:153) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5293) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by joserocha3** [comment]
@ziasultan2 in your `AndroidManifest.xml` screenshot you have `android:name=".Application"` as an attribute of `activity`. As per the [Android setup guide](https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md) it should be an attribute of `application`.

**Comment by ziasultan2** [comment]
@joserocha3 Thank you its resolved now. I'd like to change the interval time 15 to 1 for that I change the minimumFetchInterval: 1 but it's showing in logcat
03-20 11:32:21.135 3763-3763/com.ziasultan.ip_tracker D/TSBackgroundFetch: - configure: {
      "minimumFetchInterval": 15,
      "stopOnTerminate": false,
      "startOnBoot": false,
      "forceReload": false,
      "jobService": "com.transistorsoft.flutter.backgroundfetch.HeadlessJobService"
    }
will you please help me to set it to 1 minute

**Comment by christocracy** [comment]
Read the README.  The minImum fetch interval is **15 minutes**.  1 minute is *impossible*.  

Android doesn’t *want* you to abuse the user’s battery, which is what would happen with a 1 min interval.

**Comment by ziasultan2** [comment]
I'm trying to check the IP address over and over again whether it change or not. Because in cellular phone IP change from tower to tower. If change I'll send information to server. So that user doesn't got blocked by firewall.

**Comment by christocracy** [comment]
This plugin will never execute your callback any faster than every **15 minutes**.

The proper way to detect cell tower change events on Android is via [PhoneStateListener](https://developer.android.com/reference/android/telephony/PhoneStateListener.html#onCellLocationChanged(android.telephony.CellLocation), which is not within the scope of `background_fetch`.
