### ISSUE TITLE
[BUG] App crashes unexpectedly after some random period of time

### ISSUE THREAD

**Issue by TheMisir** [transistorsoft/flutter_background_fetch#180]
**Your Environment**

* Plugin version: 0.6.0
* Platform: Android
* OS version: Android 9 - Pie
* Device manufacturer / model: tissot_sprout
* Flutter info (`flutter info`, `flutter doctor`):

```
Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (7 weeks ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4
```

* Plugin config

```dart
  static Future<void> start() async {
    _logger.info('inits configrations and callback');
    BackgroundFetch.configure(
        BackgroundFetchConfig(minimumFetchInterval: 2), _callback);

    _logger.info('com.transistorsoft.deliver task registering...');
    await BackgroundFetch.scheduleTask(
      TaskConfig(
        taskId: 'com.transistorsoft.*****',
        delay: 2000,
        periodic: true,
        stopOnTerminate: false,
        forceAlarmManager: true,
        enableHeadless: true,
        requiresBatteryNotLow: false,
        requiresCharging: false,
        requiresStorageNotLow: false,
        requiresDeviceIdle: false,
      ),
    );
  }

  static void _callback(String taskId) async {
    _logger.info('callback working');
    _fireAction(taskId);
  }

  static Future<void> _fireAction(String taskId) async {
    if (taskId == 'com.transistorsoft.deliver') {
      _logger.info('firing action for $taskId');
      await globalCallback();
    }

    BackgroundFetch.finish(taskId);
  }

  Future<int> stop() => BackgroundFetch.stop('com.transistorsoft.*******');
```

**To Reproduce**
1. I don't know why exactly this happens. So I don't know how to reproduce.

**Debug logs**
- ~ios XCode logs,~
- Android: `$ adb logcat`

```
01-25 15:49:15.963 12502 12502 D AndroidRuntime: Shutting down VM
01-25 15:49:15.963 12502 12502 E AndroidRuntime: FATAL EXCEPTION: main
01-25 15:49:15.963 12502 12502 E AndroidRuntime: Process: com.******.*****, PID: ******
01-25 15:49:15.963 12502 12502 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
01-25 15:49:15.963 12502 12502 E AndroidRuntime:        at io.flutter.plugin.common.MethodChannel.setMethodCallHandler(MethodChannel.java:119)
01-25 15:49:15.963 12502 12502 E AndroidRuntime:        at io.flutter.plugins.pathprovider.PathProviderPlugin.registerWith(PathProviderPlugin.java:49)
01-25 15:49:15.963 12502 12502 E AndroidRuntime:        at com.fonibo.deliver.Application.registerWith(Application.kt:34)
01-25 15:49:15.963 12502 12502 E AndroidRuntime:        at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.startBackgroundIsolate(HeadlessTask.java:150)
01-25 15:49:15.963 12502 12502 E AndroidRuntime:        at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.dispatch(HeadlessTask.java:101)
01-25 15:49:15.963 12502 12502 E AndroidRuntime:        at com.transistorsoft.flutter.backgroundfetch.HeadlessTask.run(HeadlessTask.java:95)
01-25 15:49:15.963 12502 12502 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
01-25 15:49:15.963 12502 12502 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
01-25 15:49:15.963 12502 12502 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
01-25 15:49:15.963 12502 12502 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6762)
01-25 15:49:15.963 12502 12502 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-25 15:49:15.963 12502 12502 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-25 15:49:15.963 12502 12502 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by christocracy** [comment]
**Your Environment**
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:
* Flutter info (`flutter info`, `flutter doctor`):
* Plugin config

**Comment by christocracy** [comment]
Post you `Application.kt`

**Comment by TheMisir** [comment]
> Post your `Application.kt`

```kotlin
class Application: FlutterApplication(), PluginRegistry.PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        LocatorService.setPluginRegistrant(this)
        BackgroundFetchPlugin.setPluginRegistrant(this)
        FlutterMain.startInitialization(this)
        createChannel()
    }

    override fun registerWith(registry: PluginRegistry?) {
        if(!registry!!.hasPlugin("io.flutter.plugins.pathprovider")) {
            PathProviderPlugin.registerWith(registry!!.registrarFor("io.flutter.plugins.pathprovider"))
        }

        if(!registry!!.hasPlugin("com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin")) {
            FlutterSecureStoragePlugin.registerWith(registry!!.registrarFor("com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin"))
        }
    }

    private fun createChannel() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            // Create the NotificationChannel
           ...
        }
    }
}
```

**Comment by christocracy** [comment]
Why are you referencing the plugin in your Application.kt?

Unless you're using a very old version of Flutter (ie one year ago), the Setup docs here explicitly tell you this is not required.

**Comment by TheMisir** [comment]
> Why are you referencing the plugin in your Application.kt?
> 
> Unless you're using a very old version of Flutter (ie one year ago), the Setup docs here explicitly tell you this is not required.

I know, but when I remove that part the background plugins (eg: fcm) couldn't use native packages.

**Comment by christocracy** [comment]
Just don't do that.  I'm going to be removing that part of the Setup instructions to prevent people ever doing that now that we're a year on from the Flutter 1.12 upgrade.

Go back to the Setup and install the plugin correctly.  Get rid of that code in your Application.kt.

**Comment by TheMisir** [comment]
Okay, thank you so much 🙏
