### ISSUE TITLE
Package doesn't work, When i am executing, the App is closing.

### ISSUE THREAD

**Issue by zekihocanet** [transistorsoft/flutter_background_fetch#24]
I always see this text: "Running Gradle task 'assembleDebug'..." and it is never end.

**background_fetch**
* Plugin version: 0.2.0
* Platform: Android
* OS version: 9.0 (Pie) - API 28 
* Device manufacturer / model: Nexus 5x Emulator
* Flutter info (`flutter info`, `flutter doctor`): 

**flutter doctor**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.706], locale tr-TR)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.33.1)
[√] Connected device (1 available)

• No issues found!

AndroidManifest.xml :

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android" 
    xmlns:tools="http://schemas.android.com/tools" 
    package="com.example.back_work">

    <uses-permission android:name="android.permission.INTERNET"/>

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        tools:replace="android:label"
        android:name=".Application"
        android:label="back_work"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
</manifest>


```

**Comment by christocracy** [comment]
What do you mean "when I am executing, the app is closing"?

**Comment by zekihocanet** [comment]
PS: 
https://prnt.sc/nibmjb

**Comment by christocracy** [comment]
If your app is crashing, don't you think the stacktrace in `$ adb logcat` might contain interesting information, such as the *cause* of the crash?

**Comment by zekihocanet** [comment]
that command for mac i guess. i use windows 10.

C:\src\flutter_projects\back_work>adb logcat
'adb' is not recognized as an internal or external command,
operable program or batch file.

**Comment by christocracy** [comment]
https://www.hexnode.com/mobile-device-management/help/obtain-android-device-logs-using-windows-and-mac/

**Comment by zekihocanet** [comment]
do you mean this? >> https://prnt.sc/nibpea

**Comment by zekihocanet** [comment]
i tried my cell-phone (with usb cable) too. 
nothing has changed. i hope you'll find the problem.

**Comment by christocracy** [comment]
- Do not spam the thread with long logs.
- You don't need to post your entire logcat stream, just the *stacktrace*.  Is this your app `com.example.back_work.Application`?  I have no idea what's wrong.

```
04-29 18:31:56.219 21638 21638 E AndroidRuntime: FATAL EXCEPTION: main
04-29 18:31:56.219 21638 21638 E AndroidRuntime: Process: com.example.back_work, PID: 21638
04-29 18:31:56.219 21638 21638 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application com.example.back_work.Application: java.lang.ClassNotFoundException: Didn't find class "com.example.back_work.Application" on path: DexPathList[[zip file "/data/app/com.example.back_work-D6TEgZbXiTTII9KpNE4AbQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.back_work-D6TEgZbXiTTII9KpNE4AbQ==/lib/arm64, /data/app/com.example.back_work-D6TEgZbXiTTII9KpNE4AbQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
04-29 18:31:56.219 21638 21638 E AndroidRuntime: at android.app.LoadedApk.makeApplication(LoadedApk.java:1060)
04-29 18:31:56.219 21638 21638 E AndroidRuntime: at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5877)
04-29 18:31:56.219 21638 21638 E AndroidRuntime: at android.app.ActivityThread.access$1100(ActivityThread.java:200)
04-29 18:31:56.219 21638 21638 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1660)
04-29 18:31:56.219 21638 21638 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:106)
04-29 18:31:56.219 21638 21638 E AndroidRuntime: at android.os.Looper.loop(Looper.java:193)
04-29 18:31:56.219 21638 21638 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6762)
04-29 18:31:56.219 21638 21638 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
04-29 18:31:56.219 21638 21638 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
04-29 18:31:56.219 21638 21638 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-29 18:31:56.219 21638 21638 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.back_work.Application" on path: DexPathList[[zip file "/data/app/com.example.back_work-D6TEgZbXiTTII9KpNE4AbQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.back_work-D6TEgZbXiTTII9KpNE4AbQ==/lib/arm64, /data/app/com.example.back_work-D6TEgZbXiTTII9KpNE4AbQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
04-29 18:31:56.219 21638 21638 E AndroidRuntime: at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
04-29 18:31:56.219 21638 21638 E AndroidRuntime: at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
04-29 18:31:56.219 21638 21638 E AndroidRuntime: at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
04-29 18:31:56.219 21638 21638 E AndroidRuntime: at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50)
04-29 18:31:56.219 21638 21638 E AndroidRuntime: at android.app.Instrumentation.newApplication(Instrumentation.java:1121)
04-29 18:31:56.219 21638 21638 E AndroidRuntime: at android.app.LoadedApk.makeApplication(LoadedApk.java:1052)
04-29 18:31:56.219 21638 21638 E AndroidRuntime: ... 9 more
```

**Comment by zekihocanet** [comment]
yes that is my app's name. 

did you check my **AndroidManifest.xml**? maybe the error is there.

**Comment by christocracy** [comment]
Does your Android app have an `Application.java`?

![](https://dl.dropbox.com/s/1c0vliveib3jek9/Screenshot%202019-04-29%2012.09.39.png?dl=1)

**Comment by zekihocanet** [comment]
yes. 

![Adsız](https://user-images.githubusercontent.com/49655932/56910215-aff06100-6ab2-11e9-906b-3feeb353f9d1.png)

**Comment by christocracy** [comment]
It's assumed that you'd understand that you need to *change the namespace* of the copied `Application.java` to *your app's namespace*, which is `com.example.back_work`

```diff
+package com.example.back_work;

import com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin;
import com.transistorsoft.flutter.backgroundgeolocation.FLTBackgroundGeolocationPlugin;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class Application  extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {
    @Override
    public void onCreate() {
        super.onCreate();
        FLTBackgroundGeolocationPlugin.setPluginRegistrant(this);
        BackgroundFetchPlugin.setPluginRegistrant(this);
    }

    @Override
    public void registerWith(PluginRegistry registry) {
        GeneratedPluginRegistrant.registerWith(registry);
    }
}
```

**Comment by zekihocanet** [comment]
Yes, it is working now. Problem solved.

You must remind it, in that page:  

https://github.com/transistorsoft/flutter_background_fetch/blob/master/help/INSTALL-ANDROID.md
