### ISSUE TITLE
Error on fetch in background 

### ISSUE THREAD

**Issue by mjafartp** [transistorsoft/flutter_background_fetch#246]
**Your Environment**
* Plugin version: 1.0.1
* Platform: Android
* OS version: 7
* Device manufacturer / model: found in more than 2 models
* Flutter info (`flutter info`, `flutter doctor`): Flutter (Channel stable, 2.2.3, on Linux, locale en_IN)
* Plugin config
```
(
        minimumFetchInterval: 15,
        stopOnTerminate: false,
        enableHeadless: true,
        requiresBatteryNotLow: false,
        requiresCharging: false,
        requiresStorageNotLow: false,
        requiresDeviceIdle: false,
        startOnBoot: true,
        requiredNetworkType: NetworkType.ANY
    )
```
**To Reproduce**
1.  Start and terminate the app

Error Stack 

```
stack:#0      Sync.customerInsertToOnline (package:XXXXXX/services/sync.dart:1250)
<asynchronous suspension>
#1      Sync.insertDataToOnline (package:XXXXXX/services/sync.dart:470)
<asynchronous suspension>
#2      Sync.sync (package:XXXXXX/services/sync.dart:47)
<asynchronous suspension>
#3      _HomeState.backgroundFetchInit.<anonymous closure> (package:XXXXXX/main.dart:297)
<asynchronous suspension>
```

In the foreground, it's working without any issue.

**Comment by christocracy** [comment]
Paste your entire `HomeState` code.
