### ISSUE TITLE
[BUG] Bug on running a HeadlessTask

### ISSUE THREAD

**Issue by mjafartp** [transistorsoft/flutter_background_fetch#250]
**Your Environment**
* Plugin version: 1.0.1
* Platform: Android
* OS version: 7,9,10
* Device manufacturer / model: multipple
* Flutter info (`flutter info`, `flutter doctor`):
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.1, on Ubuntu 20.04.3 LTS 5.11.0-36-generic, locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.60.1)
[✓] Connected device (2 available)

No issues found!

* Plugin config
```
BackgroundFetchConfig(
        minimumFetchInterval: 15,
        stopOnTerminate: false,
        enableHeadless: true,
        requiresBatteryNotLow: false,
        requiresCharging: false,
        requiresStorageNotLow: false,
        requiresDeviceIdle: false,
        startOnBoot: true,
        requiredNetworkType: NetworkType.ANY
    )
```

Error Message
```
I/flutter ( 1774): [BackgroundFetch _headlessCallbackDispather] :bangbang: Callback error: type 'HeadlessTask' is not a subtype of type 'String' of '<optimized out>'
I/flutter ( 1774): #0      _TypeError._throwNew (dart:core-patch/errors_patch.dart:98)
I/flutter ( 1774): #1      _headlessCallbackDispatcher.<anonymous closure> (package:background_fetch/background_fetch.dart:652)
I/flutter ( 1774): #2      _headlessCallbackDispatcher.<anonymous closure> (package:background_fetch/background_fetch.dart:638)
I/flutter ( 1774): #3      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:435)
I/flutter ( 1774): #4      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:382)
I/flutter ( 1774): #5      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:284)
I/flutter ( 1774): #6      _invoke3.<anonymous closure> (dart:ui/hooks.dart:223)
I/flutter ( 1774): #7      _rootRun (dart:async/zone.dart:1354)
I/flutter ( 1774): #8      _CustomZone.run (dart:async/zone.dart:1258)
I/flutter ( 1774): #9      _CustomZone.runGuarded (dart:async/zone.dart:1162)
I/flutter ( 1774): #10     _invoke3 (dart:ui/hooks.dart:222)
I/flutter ( 1774): #11     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:520)
I/flutter ( 1774): #12     _dispatchPlatformMessage (dart:ui/hooks.dart:90)
```

**Comment by christocracy** [comment]
You're not providing your code?

**Comment by carman247** [comment]
In the example you are showing that the callback receives a "HeadlessTask". However, I'm using version 1.1.5 and it's passing a String

### The example code
```
@pragma('vm:entry-point')
void backgroundFetchHeadlessTask(HeadlessTask task) async {
  String taskId = task.taskId;
  bool isTimeout = task.timeout;
  if (isTimeout) {
    // This task has exceeded its allowed running-time.  
    // You must stop what you're doing and immediately .finish(taskId)
    print("[BackgroundFetch] Headless task timed-out: $taskId");
    BackgroundFetch.finish(taskId);
    return;
  }  
  print('[BackgroundFetch] Headless event received.');
  // Do your work here...
  BackgroundFetch.finish(taskId);
}
```
