### ISSUE TITLE
[BUG] Unhandled Exception: PlatformException(1, BGTaskSchedulerErrorDomain, null, null)

### ISSUE THREAD

**Issue by hosseinkhojany** [transistorsoft/flutter_background_fetch#305]
**Your Environment**
* Plugin version: background_fetch: ^1.1.2
* Platform: iOS
* OS version: 16.1
* Device manufacturer / model: iPhone simulator 14 pro
* Flutter info (`flutter info`, `flutter doctor`):

<details><summary>Click To Expand</summary>

```
javad@javads-MacBook-Air myelin_app % flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on macOS 13.0.1 22A400 darwin-arm, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
⣽^C%                                                                                                                         javad@javads-MacBook-Air myelin_app % flutter doctor -v
[✓] Flutter (Channel stable, 3.0.0, on macOS 13.0.1 22A400 darwin-arm, locale en-US)
    • Flutter version 3.0.0 at /Users/khoujani/Documents/flutter3.0.0
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (7 months ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2

[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/khoujani/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • iPhone 14 Pro (mobile) • 6378991C-3257-492E-94E8-0286FE33584E • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-1 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.0.1 22A400 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

```

</details>
* Plugin config

```dart
static Future<void> initPlatformState() async {
    if (!kIsWeb && !backgroundTaskInit) {
      try{
        await BackgroundFetch.configure(
            BackgroundFetchConfig(
              minimumFetchInterval: 15,
              stopOnTerminate: false,
              startOnBoot: true,
              enableHeadless: true,
              requiresBatteryNotLow: false,
              requiresCharging: false,
              requiresStorageNotLow: false,
              requiresDeviceIdle: false,
              requiredNetworkType: NetworkType.NONE,
            ),
            backgroundFetchTaskString, (taskId) {
          print("TIMOUT FETCH");
          BackgroundFetch.finish(taskId);
        });
        // backgroundFetchTask("");
        backgroundTaskInit = true;
      }on Exception catch(e){
        e.printError();
      }
    }
  }
```

```dart
Future<void> _scheduleTask(DateTime schedule, {@required bool asAlarm}) async {
  String taskID = asAlarm ? AppStrings.alarmTaskID : AppStrings.reminderTaskID;
  print("Task Scheduled: $taskID TIME: ${schedule.difference(DateTime.now()).toString()}");
  if (!kIsWeb) {
    BackgroundFetch.scheduleTask(TaskConfig(
        taskId: taskID,
        delay: schedule.difference(DateTime.now()).inMilliseconds,
        periodic: false,
        forceAlarmManager: true,
        stopOnTerminate: false,
        enableHeadless: true));
  }
}
```

**Debug logs**
```
[VERBOSE-2:ui_dart_state.cc(198)] Unhandled Exception: PlatformException(1, BGTaskSchedulerErrorDomain, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
<asynchronous suspension>
#2      BackgroundFetch.scheduleTask (package:background_fetch/background_fetch.dart:566:12)
<asynchronous suspension>
```
**Additional context**
This problem does not exist in Android and it works properly

**Comment by christocracy** [comment]
>Device manufacturer / model: iPhone simulator 14 pro
>PlatformException(1, BGTaskSchedulerErrorDomain, null, null)

See [here](https://developer.apple.com/documentation/backgroundtasks/bgtaskschedulererrorcode/bgtaskschedulererrorcodeunavailable?language=objc)

You can't test this in an iOS Simulator.  It only works on a real device.

[(20221107115828).csv](https://github.com/transistorsoft/flutter_background_fetch/files/10155110/20221107115828.csv)
