### ISSUE TITLE
Does not run automatically in background or after termination. Myapp's main.dart has minimal code as I prefer everything managed, hence missing something while implementing this plug in.

### ISSUE THREAD

**Issue by kazi41571** [transistorsoft/flutter_background_fetch#32]
Since I have called the check() , it runs only for the first time.

> flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.15063], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.36.0)
[√] VS Code, 64-bit edition (version 1.26.1)
[√] Connected device (1 available)

• No issues found!

This is my main.dart

```dart
void main() {
  FlutterError.onError = (FlutterErrorDetails details) async {
    if (AppGlobals.isInDebugMode) {
      FlutterError.dumpErrorToConsole(details);
    } else {
      Zone.current.handleUncaughtError(details.exception, details.stack);
    }
  };

  runZoned<Future<Null>>(() async {
    runApp(MyApp());
    BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
    
  }, onError: (error, stackTrace) async {
    await AppGlobals.reportError(error, stackTrace);
  });
}
//my material app home is as below
home: SplashScreen(),

//my splash screen code is as below

void backgroundFetchHeadlessTask() async {
  print('[BackgroundFetch] Headless event received.');

  SharedPreferences pref = await SharedPreferences.getInstance();
  List<DocumentMaster> _lstDocumentMaster = new List<DocumentMaster>();
  List<DocumentMaster> lstDocumentMasterTemp;
  _lstDocumentMaster.clear();
  if (pref.getString("Username") != null && pref.getString("Username") != "") {
    int userMasterId = int.parse(pref.getString("UserMasterId"));
    lstDocumentMasterTemp =
        await DocumentMasterParser().selectAllDocumentMasterCheck(userMasterId);
    _lstDocumentMaster.addAll(lstDocumentMasterTemp);
  }

  BackgroundFetch.finish();
}

 @override
  void initState() {
    super.initState();

    BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
    initPlatformState();

    _streamSubscription = new Connectivity()
        .onConnectivityChanged
        .listen((ConnectivityResult result) {
      AppGlobals.isInternetAvailable().then((value) {
        _isInternet = value;
        if (value) {
          loadSplashScreen();
        } else {
          setState(() {});
        }
      });
    });
  }

//check() calls api 
 check() async {
    List<DocumentMaster> lstDocumentMasterTemp;

    _lstDocumentMaster.clear();
    SharedPreferences pref = await SharedPreferences.getInstance();
    if (pref.getString("Username") != null &&
        pref.getString("Username") != "") {
      int userMasterId = int.parse(pref.getString("UserMasterId"));
      lstDocumentMasterTemp = await DocumentMasterParser()
          .selectAllDocumentMasterCheck(userMasterId);

      _lstDocumentMaster.addAll(lstDocumentMasterTemp);
      // AppGlobals.showMessage(
      //     _lstDocumentMaster.length.toString(), MessageType.information);
      setState(() {});
    }
  }
//below are your functions after removing unwanted code in my case
Future<void> initPlatformState() async {
    // Load persisted fetch events from SharedPreferences

    // Configure BackgroundFetch.
    BackgroundFetch.configure(
            BackgroundFetchConfig(
                minimumFetchInterval: 15,
                stopOnTerminate: false,
                enableHeadless: true,
                forceReload: false),
            _onBackgroundFetch)
        .then((int status) {
     

      print('[BackgroundFetch] SUCCESS: $status');
      check();

      setState(() {
        //_status = status;
      });
    }).catchError((e) {
      print('[BackgroundFetch] ERROR: $e');
      setState(() {
        //_status = e;
      });
    });

    // Optionally query the current BackgroundFetch status.
    //int status = await BackgroundFetch.status;
    setState(() {
      //_status = status;
    });

    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;
  }

  void _onBackgroundFetch() async {
    //SharedPreferences prefs = await SharedPreferences.getInstance();

    // This is the fetch-event callback.
    print('[BackgroundFetch] Event received');
    check();
    setState(() {
      //_events.insert(0, new DateTime.now().toString());
    });
    // Persist fetch events in SharedPreferences
    //prefs.setString(EVENTS_KEY, jsonEncode(_events));

    // IMPORTANT:  You must signal completion of your fetch task or the OS can punish your app
    // for taking too long in the background.
    BackgroundFetch.finish();
  }
```

**Comment by kazi41571** [comment]
package com.example.dms;

import com.transistorsoft.flutter.backgroundfetch.BackgroundFetchPlugin;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class Application extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {
    @Override
    public void onCreate() {
        super.onCreate();
        BackgroundFetchPlugin.setPluginRegistrant(this);
    }

    @Override
    public void registerWith(PluginRegistry registry) {
        GeneratedPluginRegistrant.registerWith(registry);
    }
}

**Comment by christocracy** [comment]
The following information was requested in the issue template:

**Your Environment**
* Plugin version:
* Platform: iOS or Android
* OS version:
* Device manufacturer / model:

**Comment by kazi41571** [comment]
Plugin version: background_fetch: ^0.1.0
    Platform: iOS or Android: Android
    OS version: Windows
    Device manufacturer / model:Redmi Note 4

**Comment by christocracy** [comment]
Have you tried the `/example` app in this repo and [simulated a fetch event as documented in the README](https://github.com/transistorsoft/flutter_background_fetch#android)?

I just booted the `/example` app on the following devices and all work after terminate and device reboot:
- Samsung A5 @ 8.0.0
- Pixel 3a @ 9.0.0
- Xiomi Mi A2 Lite @ 9.0.0


```
$ adb shell cmd jobscheduler run -f com.transistorsoft.flutter.backgroundfetch.backgroundfetchexample 999
```

```
07-04 09:37:05.594 20122 20122 D TSBackgroundFetch: - Background Fetch event received
07-04 09:37:05.602 20122 20122 D TSBackgroundFetch: - finish
07-04 09:37:05.602 20122 20122 D TSBackgroundFetch: - jobFinished
07-04 09:37:05.615 20122 20122 D TSBackgroundFetch: HeadlessJobService onStartJob
07-04 09:37:05.615 20122 20122 D TSBackgroundFetch: 💀 [HeadlessTask]
07-04 09:37:05.854 20122 20122 D TSBackgroundFetch: [HeadlessTask] waiting for client to initialize
07-04 09:37:06.042 20122 20145 I flutter : Observatory listening on http://127.0.0.1:40328/CpWmxVn7h0k=/
07-04 09:37:06.516 20122 20122 I TSBackgroundFetch: $ initialized
07-04 09:37:06.589 20122 20142 I flutter : [BackgroundFetch] Headless event received.
07-04 09:37:06.779 20122 20122 D TSBackgroundFetch: - finish
07-04 09:37:06.779 20122 20122 D TSBackgroundFetch: HeadlessJobService jobFinished
```

**Comment by christocracy** [comment]
Also see http://dontkillmyapp.com

**Comment by kazi41571** [comment]
Forced events are received successfully, But unable to receive anything automatically.

**Comment by christocracy** [comment]
If simulated events work, that's all you need to do to know it works.  Everything else is up to Android (and your device vendors specific flavour of Android).  If your particular device isn't working, see http://dontkillmyapp.com

**Comment by kazi41571** [comment]
flutter run --release
Initializing gradle...                                              1.0s
Resolving dependencies...                                           4.0s
Launching lib/main.dart on Redmi Note 4 in release mode...
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      45.2s
Built build\app\outputs\apk\release\app-release.apk (6.9MB).
Installing build\app\outputs\apk\app.apk...                         7.5s

To quit, press "q".
I/flutter (28673): [BackgroundFetch] SUCCESS: 2

**Comment by kazi41571** [comment]
adb logcat *:S flutter:V, TSBackgroundFetch:V
--------- beginning of crash
--------- beginning of system
--------- beginning of main
07-04 19:28:56.720 28673 28673 D TSBackgroundFetch: - configure: {
07-04 19:28:56.720 28673 28673 D TSBackgroundFetch:   "minimumFetchInterval": 15,
07-04 19:28:56.720 28673 28673 D TSBackgroundFetch:   "stopOnTerminate": false,
07-04 19:28:56.720 28673 28673 D TSBackgroundFetch:   "startOnBoot": false,
07-04 19:28:56.720 28673 28673 D TSBackgroundFetch:   "forceReload": false,
07-04 19:28:56.720 28673 28673 D TSBackgroundFetch:   "jobService": "com.transistorsoft.flutter.backgroundfetch.HeadlessJobService"
07-04 19:28:56.720 28673 28673 D TSBackgroundFetch: }
07-04 19:28:56.720 28673 28673 D TSBackgroundFetch: - start
07-04 19:28:56.730 28673 28746 I flutter : [BackgroundFetch] SUCCESS: 2

**Comment by kazi41571** [comment]
First time my api is called successfully but then later on its never been called.
Then when i write this command for forced , the result is success i.e again the api is called succesfully
adb shell cmd jobscheduler run -f com.example.dms 999
Running job [FORCED]

**Comment by kazi41571** [comment]
Kindly check my main.dart and splashscreen code, wonder if i am missing anything.

**Comment by kazi41571** [comment]
Also I am writing this line
initPlatformState();

in my splashscreen initState method and not in main.darts initmethod, is it right?

**Comment by kazi41571** [comment]
07-04 19:32:49.032 28673 28673 D TSBackgroundFetch: - Background Fetch event received
07-04 19:32:49.039 28673 28746 I flutter : [BackgroundFetch] Event received
07-04 19:35:03.217 28673 28673 D TSBackgroundFetch: - onStopJob
07-04 19:36:40.318 28673 28673 D TSBackgroundFetch: - Background Fetch event received
07-04 19:36:40.319 28673 28746 I flutter : [BackgroundFetch] Event received



In the above log the first time my api is called at 19:32:50 but after that is didnt call, thats my question.

**Comment by christocracy** [comment]
```
BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
```
As long as `backgroundFetchHeadlessTask` is available in that context (it is) and `backgroundFetchHeadlessTask` exists in `main.dart` (it does), it should be fine.

I'm only concerned with "does the fetch event get received by simulating an event".  I'm not concerned by "after that is didnt call".

If your headless event fires by simulating after terminating your app, everything is configured correctly.  After that, it's up to your OS.

**Comment by kazi41571** [comment]
Thanks for your detailed review. 99% things are correct, but i am not getting headless events in my app, which i was getting in your example.
I terminated the app from recent list and forced event but it didn't log anything that means

**Comment by kazi41571** [comment]
Regarding your example, After backing 2 times and exiting the app still i get headless event, fine. But after removing from memory/recently list, simulated event is not logged. then again i opened the app to check the logs but it didnt get that event. neither in list nor in log.

**Comment by kazi41571** [comment]
I know its getting too long bro but this is the log i am getting and everytime my device shows your app keeps stopping.
07-05 15:06:36.010 20718 20718 D TSBackgroundFetch: HeadlessJobService onStartJob
07-05 15:06:36.010 20718 20718 D TSBackgroundFetch: 💀 [HeadlessTask]
07-05 15:07:08.845 20825 20825 D TSBackgroundFetch: HeadlessJobService onStartJob
07-05 15:07:08.848 20825 20825 D TSBackgroundFetch: 💀 [HeadlessTask]
07-05 15:08:10.972 21033 21033 D TSBackgroundFetch: HeadlessJobService onStartJob
07-05 15:08:10.981 21033 21033 D TSBackgroundFetch: 💀 [HeadlessTask]
07-05 15:10:15.754 21206 21206 D TSBackgroundFetch: HeadlessJobService onStartJob
07-05 15:10:15.757 21206 21206 D TSBackgroundFetch: 💀 [HeadlessTask]
07-05 15:14:18.435 21628 21628 D TSBackgroundFetch: HeadlessJobService onStartJob
07-05 15:14:18.438 21628 21628 D TSBackgroundFetch: 💀 [HeadlessTask]
07-05 15:18:31.722 22489 22489 D TSBackgroundFetch: - Background Fetch event received
07-05 15:18:31.735 22489 22489 D TSBackgroundFetch: - finish
07-05 15:18:31.735 22489 22489 D TSBackgroundFetch: - jobFinished
07-05 15:18:31.870 22489 22489 D TSBackgroundFetch: HeadlessJobService onStartJob
07-05 15:18:31.870 22489 22489 D TSBackgroundFetch: 💀 [HeadlessTask]
07-05 15:18:32.146 22489 22489 D TSBackgroundFetch: [HeadlessTask] waiting for client to initialize
07-05 15:18:32.292 22489 22489 I TSBackgroundFetch: $ initialized
07-05 15:18:32.301 22489 22508 I flutter : [BackgroundFetch] Headless event received.
07-05 15:18:32.302 22489 22508 I flutter : Hi Faiz. Background headless fetch successful
07-05 15:18:32.312 22489 22489 D TSBackgroundFetch: - finish
07-05 15:18:32.312 22489 22489 D TSBackgroundFetch: HeadlessJobService jobFinished
07-05 15:21:13.572 23387 23387 D TSBackgroundFetch: - Background Fetch event received
07-05 15:21:13.577 23387 23387 D TSBackgroundFetch: - finish
07-05 15:21:13.577 23387 23387 D TSBackgroundFetch: - jobFinished
07-05 15:21:13.704 23387 23387 D TSBackgroundFetch: HeadlessJobService onStartJob
07-05 15:21:13.704 23387 23387 D TSBackgroundFetch: 💀 [HeadlessTask]
07-05 15:21:55.509 23591 23591 D TSBackgroundFetch: HeadlessJobService onStartJob
07-05 15:21:55.522 23591 23591 D TSBackgroundFetch: 💀 [HeadlessTask]
07-05 15:22:59.883 23681 23681 D TSBackgroundFetch: HeadlessJobService onStartJob
07-05 15:22:59.887 23681 23681 D TSBackgroundFetch: 💀 [HeadlessTask]
07-05 15:25:01.025 24076 24076 D TSBackgroundFetch: HeadlessJobService onStartJob
07-05 15:25:01.032 24076 24076 D TSBackgroundFetch: 💀 [HeadlessTask]

**Comment by kazi41571** [comment]
after 15 minutes it ran in the background by crashing the app.

07-05 17:12:09.267 21588 21588 D TSBackgroundFetch: - jobFinished
07-05 17:27:09.484 25017 25017 D TSBackgroundFetch: - Background Fetch event received
07-05 17:27:09.493 25017 25017 D TSBackgroundFetch: - finish
07-05 17:27:09.493 25017 25017 D TSBackgroundFetch: - jobFinished
07-05 17:27:09.624 25017 25017 D TSBackgroundFetch: HeadlessJobService onStartJob
07-05 17:27:09.625 25017 25017 D TSBackgroundFetch: 💀 [HeadlessTask]

**Comment by kazi41571** [comment]
From crash summary i am getting this. Any idea or hint from this?

java.lang.RuntimeException: java.lang.IllegalStateException: registrar.activity() must not be null
	at android.app.job.JobService$JobHandler.handleMessage(JobService.java:147)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:165)
	at android.app.ActivityThread.main(ActivityThread.java:6375)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
Caused by: java.lang.IllegalStateException: registrar.activity() must not be null
	at com.a.a.a.a$a.a(Unknown Source)
	at com.a.a.a.a.a(Unknown Source)
	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source)
	at com.example.dms.Application.registerWith(Unknown Source)
	at com.transistorsoft.flutter.backgroundfetch.b.b(Unknown Source)
	at com.transistorsoft.flutter.backgroundfetch.b.<init>(Unknown Source)
	at com.transistorsoft.flutter.backgroundfetch.HeadlessJobService.onStartJob(Unknown Source)
	at android.app.job.JobService$JobHandler.handleMessage(JobService.java:143)
	... 6 more

**Comment by christocracy** [comment]
See #11

**Comment by kazi41571** [comment]
I read that just now, it says something about flutter blue plugin. Am not able to understand what exact steps i need to take.

**Comment by christocracy** [comment]
One of your *other plugins* is executing registrar.activity() and assuming it’s not null in the Headless state.  There is no activity in the Headless state.  Show me your dependencies from pubspec.yaml

**Comment by kazi41571** [comment]
cupertino_icons: ^0.1.2

  connectivity: ^0.4.3+2
  fluttertoast: ^3.0.4
  flutter_colorpicker: ^0.2.3
  flutter_statusbarcolor: ^0.2.0
  flutter_udid: ^1.0.0
  shared_preferences: ^0.5.3+1
  intl: ^0.15.8
  http: ^0.12.0+2
  image_picker: ^0.6.0+7
  libcalendar: ^0.2.0  
  flutter_launcher_icons: ^0.7.2
  outline_material_icons: ^0.1.0
  flutter_typeahead: ^1.6.1
  background_fetch: ^0.2.0

**Comment by christocracy** [comment]
Now go check the Android source of each of your plugins.  Check the [registerWith](https://github.com/transistorsoft/flutter_background_geolocation/blob/master/android/src/main/java/com/transistorsoft/flutter/backgroundgeolocation/FLTBackgroundGeolocationPlugin.java#L89-L102) (and associated plugin constructor) for usage of `registrar.activity()`.  Plugin's should first do a `!= null` check before using it, as `flutter_background_geolocation` does in the previous link.

**Comment by christocracy** [comment]
For example, [flutter_statusbarcolor](https://github.com/mchome/flutter_statusbarcolor/blob/master/android/src/main/kotlin/com/fuyumi/flutterstatusbarcolor/flutterstatusbarcolor/FlutterStatusbarcolorPlugin.kt#L18) is *not* checking if `registrar.activity() != null` before using it.

It should be doing this:
```diff
fun registerWith(registrar: Registrar): Unit {
            val channel = MethodChannel(registrar.messenger(), "plugins.fuyumi.com/statusbar")
+            if (registrar.activity() != null) {
                  channel.setMethodCallHandler(FlutterStatusbarcolorPlugin(registrar.activity()))
+            }
        }
```

**Comment by christocracy** [comment]
If you open the folder  /android in Android Studio, you can operate upon each plugin adding a null check where required.

When you find them all, the plugin authors should be notified and/or pull-request submitted to them.

**Comment by kazi41571** [comment]
I changed the lines as you mentioned and now the exception has changed which i am unable to find.
java.lang.RuntimeException: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Application android.app.Activity.getApplication()' on a null object reference
	at android.app.job.JobService$JobHandler.handleMessage(JobService.java:147)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:165)
	at android.app.ActivityThread.main(ActivityThread.java:6375)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Application android.app.Activity.getApplication()' on a null object reference
	at com.b.a.a.a.a(Unknown Source)
	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source)
	at com.example.dms.Application.registerWith(Unknown Source)
	at com.transistorsoft.flutter.backgroundfetch.b.b(Unknown Source)
	at com.transistorsoft.flutter.backgroundfetch.b.<init>(Unknown Source)
	at com.transistorsoft.flutter.backgroundfetch.HeadlessJobService.onStartJob(Unknown Source)
	at android.app.job.JobService$JobHandler.handleMessage(JobService.java:143)
	... 6 more

**Comment by christocracy** [comment]
Again, this is one of your misbehaved 3rd party plugins failing to take account for null Activity.

android.app.Application android.app.Activity.getApplication()' on a null object reference
at com.b.a.a.a.a(Unknown Source)

**Comment by kazi41571** [comment]
Ok i will remove all the plugins and add one by one. No other way of finding the source. right?

**Comment by christocracy** [comment]
That should do it.

**Comment by kazi41571** [comment]
After informing the flutter_statusbarcolor plugin developer, they updated their version and it works as you suggested. One of these two other plugins might have the same issue, have not confirmed or informed them yet but for the time being i don't need them (flutter_typeahead and flutter_launcher_icons).

Conclusively, now my app runs fine and get headless event after following your dontkillmyapp link for my miui10 . Thank you very much for your plugin and efficient support. Great work,

**Comment by debasmitasarkar** [comment]
I am also facing the same issue in my oneplus even after forcing the background fetch it does not logging or running anything. @christocracy

**Comment by christocracy** [comment]
@debasmitasarkar this issue is closed and you're providing no information.

**Comment by debasmitasarkar** [comment]
@christocracy I know this issue is closed. But it is not clear to me. I have copied your example code and tried to run in main.dart.

**Comment by christocracy** [comment]
I suggest you post a new issue.

**Comment by harivamshi81189** [comment]
> The following information was requested in the issue template:
> 
> **Your Environment**
> 
> * Plugin version:
> * Platform: iOS or Android
> * OS version:
> * Device manufacturer / model:

will headless tasks work on iOS?

**Comment by christocracy** [comment]
iOS has no concept of “running headless”.  That’s an Android-only concept.

**Comment by harivamshi81189** [comment]
> iOS has no concept of “running headless”. That’s an Android-only concept.

I mean like after app termination. Will the background process work after the app gets terminated on iOS?

**Comment by christocracy** [comment]
iOS will resume tracking after terminate when the device moves *at least* 200 meters.  Read the API docs `Config.stopOnTerminate` -- the behaviour of iOS is fully explained there.

**Comment by harivamshi81189** [comment]
I am unable to find it in API docs ( https://pub.dev/documentation/background_fetch/latest/background_fetch/BackgroundFetch-class.html )

Can you please include the link here to the location you are referring to?

**Comment by christocracy** [comment]
Sorry, I thought we were talking about [flutter_background_geolocation](https://github.com/transistorsoft/flutter_background_geolocation).  Ignore what I wrote above.

>I mean like after app termination. Will the background process work after the app got terminated on iOS?

iOS stops firing background-fetch events when *user* terminates the app.

**Comment by harivamshi81189** [comment]
> Sorry, I thought we were talking about [flutter_background_geolocation](https://github.com/transistorsoft/flutter_background_geolocation). Ignore what I wrote above.
> 
> > I mean like after app termination. Will the background process work after the app got terminated on iOS?
> 
> iOS stops firing background-fetch events when _user_ terminates the app. There's no such thing as `stopOnTerminate: false` for iOS background_fetch. `stopOnTerminate: false` only works for Android.

Ohh...So there is no way to execute task after the app termination in iOS?

**Comment by christocracy** [comment]
>So there is no way to execute task after the app termination in iOS?

That's correct.  This is Apple's decision.

**Comment by harivamshi81189** [comment]
> > So there is no way to execute task after the app termination in iOS?
> 
> That's correct. This is Apple's decision.

Thank you so much for giving clarity...I have been searching for this a lot and got a clarification now.

**Comment by christocracy** [comment]
And even if the user *doesn't* terminate your iOS app -- if they don't bring your iOS app into the foreground *daily*, iOS will pause fetch events.

**Comment by christocracy** [comment]
This repo contains an `/example` app which logs received events into a list.  Run the example on your device to monitor long-term log of received events.

**Comment by razaadn** [comment]
@christocracy is there any alternate for IOS Background Fetch to get work done in Background for IOS

**Comment by christocracy** [comment]
No
