### ISSUE TITLE
[BUG] MissingPluginException(No implementation found for method finish)

### ISSUE THREAD

**Issue by alpapado** [transistorsoft/flutter_background_fetch#332]
I get the above exception when simulating a BackgroundFetch event **after restarting the app.**:

Initially, there is no problem --> The events are received and the callback runs correctly
However, if I restart the app (by swiping it left and restarting it), then, for any new fetch events I get `No implementation found for method finish`.

This happens regardless of whether I setup a headless callback. (in the code below I don't but it seems to have no effect on the problem)

**MacOS**
* Plugin version: **1.1.6**
* Platform: **Android**
* OS version: **Android 13**
* Device manufacturer / model: **Redmi Note 10 5G**
* Flutter info (`flutter info`, `flutter doctor`):
```
[!] Flutter (Channel stable, 3.10.1, on macOS 13.0.1 22A400 darwin-arm64, locale en-GR)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/2.16.1/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/mug/Programs/flutter. Consider adding /Users/mug/Programs/flutter/bin
      to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
[✓] Connected device (2 available)
[✓] Network resources
```
* Plugin config
```
BackgroundFetchConfig(
    minimumFetchInterval: 15,
    stopOnTerminate: false,
    startOnBoot: true,
    enableHeadless: true,
    requiresBatteryNotLow: false,
    requiresCharging: false,
    requiresStorageNotLow: false,
    requiresDeviceIdle: false,
    requiredNetworkType: NetworkType.NONE,
  );
```

**To Reproduce**
1. Run application
2. Simulate event --> Works ok
3. Kill the app by swiping it left
4. Re-open the app and simulate another event --> Missing plugin exception

**Debug logs**
- Android: `$ adb logcat`
```
D/TSBackgroundFetch(24871): - Background Fetch event received: flutter_background_fetch
I/flutter (24871): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (24871): │ #0   BackgroundService._onBackgroundFetch (package:rebecca_patient_app/src/background/background_service.dart:62:12)
I/flutter (24871): │ #1   BackgroundFetch.configure.<anonymous closure> (package:background_fetch/background_fetch.dart:446:18)
I/flutter (24871): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (24871): │ 💡 [BackgroundFetch] Event received flutter_background_fetch
I/flutter (24871): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
E/flutter (24871): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method finish on channel com.transistorsoft/flutter_background_fetch/methods)
E/flutter (24871): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
E/flutter (24871): <asynchronous suspension>
E/flutter (24871): 
D/TSBackgroundFetch(24871): [BGTask] timeout: flutter_background_fetch
I/flutter (24871): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (24871): │ #0   BackgroundService._onBackgroundFetchTimeout (package:rebecca_patient_app/src/background/background_service.dart:71:12)
I/flutter (24871): │ #1   BackgroundFetch.configure.<anonymous closure> (package:background_fetch/background_fetch.dart:444:22)
I/flutter (24871): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (24871): │ 💡 [BackgroundFetch] TASK TIMEOUT taskId: flutter_background_fetch
I/flutter (24871): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
E/flutter (24871): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method finish on channel com.transistorsoft/flutter_background_fetch/methods)
E/flutter (24871): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:308:7)
E/flutter (24871): <asynchronous suspension>
```

**Additional context**
As far as I can tell, I don't get this problem when running the example app. So I suppose this is an issue on my part, but for the life of me I can't figure it out. I have followed the setup guide religiously. 

I use the following code for setting up the plugin:
```
import 'package:background_fetch/background_fetch.dart';
import 'package:logger/logger.dart';

@pragma('vm:entry-point')
class BackgroundService {
  static final logger = Logger();

  static final backgroundFetchConfig = BackgroundFetchConfig(
    minimumFetchInterval: 15,
    stopOnTerminate: false,
    startOnBoot: true,
    enableHeadless: true,
    requiresBatteryNotLow: false,
    requiresCharging: false,
    requiresStorageNotLow: false,
    requiresDeviceIdle: false,
    requiredNetworkType: NetworkType.NONE,
  );

  // ANDROID-ONLY
  @pragma('vm:entry-point')
  static void headlessCallback(HeadlessTask task) async {
    String taskId = task.taskId;
    bool isTimeout = task.timeout;
    if (isTimeout) {
      // This task has exceeded its allowed running-time.
      // You must stop what you're doing and immediately .finish(taskId)
      logger.i("[BackgroundFetch] Headless task timed-out: $taskId");
      BackgroundFetch.finish(taskId);
      return;
    }
    logger.i('[BackgroundFetch] Headless event received: $taskId');
    // Do your work here...
    BackgroundFetch.finish(taskId);
  }

  Future<void> setup() async{
    int status = await BackgroundFetch.configure(backgroundFetchConfig, _onBackgroundFetch, _onBackgroundFetchTimeout);
    // await BackgroundFetch.registerHeadlessTask(headlessCallback);
    logger.i('[BackgroundFetch] configure success: $status');
  }

  static void _onBackgroundFetch(String taskId) async{
    logger.i("[BackgroundFetch] Event received $taskId");
    BackgroundFetch.finish(taskId);
  }

  static void _onBackgroundFetchTimeout(String taskId) {
    logger.i("[BackgroundFetch] TASK TIMEOUT taskId: $taskId");
    BackgroundFetch.finish(taskId);
  }
}

```

and I call `BackgroundService.setup()` in the `initState` of the home page as per the example app.

Any idea what I am missing here?

**Comment by christocracy** [comment]
Can you reproduce this in a simple HelloWorld app and share it with me in a public GitHub repo?

**Comment by alpapado** [comment]
Thanks for your quick reply.

While trying to reproduce this in a simple app, I came to the realization that the problem is caused by my simultaneous use of the [background_locator_2](https://pub.dev/packages/background_locator_2) plugin! 

Something with this plugin creating an isolate for recording location in the background seems to mess up the registration of the other plugins I guess. Will have to investigate further. 

However, it seems that this is not an issue with flutter_background_fetch.

**Comment by christocracy** [comment]
Are you aware that I’m the creator of [flutter_background_geolocation](https://pub.dev/packages/flutter_background_geolocation), supported full time for over 8 years?

**Comment by christocracy** [comment]
My `background_fetch` is *precisely* designed as a companion for `background_geolocation`

**Comment by alpapado** [comment]
> Are you aware that I’m the creator of [flutter_background_geolocation](https://pub.dev/packages/flutter_background_geolocation), supported full time for over 8 years?

I am now. I will check it out
