### ISSUE TITLE
[BUG] iOS Usage

### ISSUE THREAD

**Issue by melihcelik09** [transistorsoft/flutter_background_fetch#379]
* Plugin version: 1.3.7
* Platform: iOS 
* OS version: Sequoia 15

I followed ios setup on documentation but i got a error someone help me how to fix this issue?

### Error
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(0, Background procssing task was not registered in AppDelegate didFinishLaunchingWithOptions.  See iOS Setup Guide., null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
message_codecs.dart:648
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
platform_channel.dart:334
<asynchronous suspension>
#2      BackgroundFetch.scheduleTask (package:background_fetch/background_fetch.dart:572:12)
background_fetch.dart:572
<asynchronous suspension>
```

###  AppDelegate.swift File

```
import Flutter
import UIKit

@main
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
      GeneratedPluginRegistrant.register(with: self)
      return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```
### My complete code

```
import 'package:background_fetch/background_fetch.dart';
import 'package:flutter/material.dart';
import 'package:home_widget_implementation/home_widget_manager.dart';

final HomeWidgetManager manager = HomeWidgetManager.instance;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await manager.init();
  await manager.background(callback: callback);
  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
  runApp(const MyApp());
}

@pragma('vm:entry-point')
void backgroundFetchHeadlessTask(HeadlessTask task) async {
  if (task.timeout) {
    debugPrint("[BackgroundFetch] Headless task timeout: ${task.taskId}");
    BackgroundFetch.finish(task.taskId);
    return;
  }

  debugPrint("[BackgroundFetch] Headless event received.");
  await _refresh();

  if (task.taskId == 'flutter_background_fetch') {
    BackgroundFetch.scheduleTask(TaskConfig(
      taskId: "com.transistorsoft.fetch",
      delay: 5000,
      periodic: false,
      forceAlarmManager: false,
      stopOnTerminate: false,
      enableHeadless: true,
    ));
  }
  BackgroundFetch.finish(task.taskId);
  debugPrint("[BackgroundFetch] Headless task completed: ${task.taskId}");
}

enum HomeWidgetAction { refresh }

enum HomeWidgetKeys { salary, usedAnnualLeave, remainingAnnualLeave }

@pragma('vm:entry-point')
Future<void> callback(Uri? uri) async {
  if (uri?.host == HomeWidgetAction.refresh.name) {
    await _refresh();
  } else {
    debugPrint("Unknown intent: ${uri?.host}");
  }
}

Future<void> _fetch() async {
  await Future.delayed(const Duration(seconds: 2));
  await Future.wait([
    manager.save(name: HomeWidgetKeys.usedAnnualLeave.name, value: 10),
    manager.save(name: HomeWidgetKeys.remainingAnnualLeave.name, value: 10),
    manager.save(name: HomeWidgetKeys.salary.name, value: 1000),
  ]);

  await manager.update();
}

Future<void> _refresh() async {
  await _fetch();
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with WidgetsBindingObserver {
  final TextEditingController _salary = TextEditingController();
  final TextEditingController _usedAnnualLeave = TextEditingController();
  final TextEditingController _remainingAnnualLeave = TextEditingController();
  bool isLoading = false;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _initializeHomeWidget();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    if (state == AppLifecycleState.resumed) {
      setState(() {});
    }
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  Future<void> _initializeHomeWidget() async {
    await manager.init();
    await _fetch();

    try {
      await BackgroundFetch.configure(
        BackgroundFetchConfig(
          minimumFetchInterval: 15,
          forceAlarmManager: false,
          stopOnTerminate: false,
          startOnBoot: true,
          enableHeadless: true,
          requiresBatteryNotLow: false,
          requiresCharging: false,
          requiresStorageNotLow: false,
          requiresDeviceIdle: false,
          requiredNetworkType: NetworkType.NONE,
        ),
        onBackgroundFetch,
        onBackgroundFetchTimeOut,
      );
      BackgroundFetch.scheduleTask(TaskConfig(
        taskId: "com.transistorsoft.fetch",
        delay: 10000,
        periodic: false,
        forceAlarmManager: true,
        stopOnTerminate: false,
        enableHeadless: true,
      ));
    } on Exception catch (e) {
      debugPrint("[BackgroundFetch] ERROR: $e");
    }
  }

  void onBackgroundFetch(String taskId) async {
    debugPrint("[BackgroundFetch] Event Received: $taskId");
    BackgroundFetch.finish(taskId);
  }

  void onBackgroundFetchTimeOut(String taskId) async {
    debugPrint("[BackgroundFetch] TIMEOUT: $taskId");
    BackgroundFetch.finish(taskId);
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Home Widget Example'),
        ),
        body: Center(
          child: Padding(
            padding: const EdgeInsets.all(8.0),
            child: Wrap(
              alignment: WrapAlignment.end,
              runSpacing: 20,
              children: <Widget>[
                TextField(
                  controller: _salary,
                  decoration: const InputDecoration(
                    border: OutlineInputBorder(),
                    hintText: 'Salary',
                  ),
                ),
                TextField(
                  controller: _usedAnnualLeave,
                  decoration: const InputDecoration(
                    border: OutlineInputBorder(),
                    hintText: 'Used Annual Leaves',
                  ),
                ),
                TextField(
                  controller: _remainingAnnualLeave,
                  decoration: const InputDecoration(
                    border: OutlineInputBorder(),
                    hintText: 'Remaining Annual Leaves',
                  ),
                ),
                ElevatedButton(
                  onPressed: () async {
                    setState(() {
                      isLoading = true;
                    });
                    await Future.wait([
                      manager.save(
                          name: HomeWidgetKeys.salary.name,
                          value: _salary.text),
                      manager.save(
                          name: HomeWidgetKeys.usedAnnualLeave.name,
                          value: _usedAnnualLeave.text),
                      manager.save(
                          name: HomeWidgetKeys.remainingAnnualLeave.name,
                          value: _remainingAnnualLeave.text),
                      manager.update(),
                    ]);
                    await Future.delayed(const Duration(seconds: 1));

                    setState(() {
                      isLoading = false;
                    });
                  },
                  child: isLoading
                      ? const CircularProgressIndicator.adaptive()
                      : const Text('Save Data'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
```

**Comment by christocracy** [comment]
Post your Info.plist

**Comment by melihcelik09** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CADisableMinimumFrameDurationOnPhone</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>$(DEVELOPMENT_LANGUAGE)</string>
	<key>CFBundleDisplayName</key>
	<string>Home Widget Implementation</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>home_widget_implementation</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>$(FLUTTER_BUILD_NAME)</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>$(FLUTTER_BUILD_NUMBER)</string>
	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>UIApplicationSupportsIndirectInputEvents</key>
	<true/>
	<key>UIBackgroundModes</key>
	<array>
		<string>fetch</string>
		<string>processing</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIMainStoryboardFile</key>
	<string>Main</string>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>UISupportedInterfaceOrientations~ipad</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
		<string>UIInterfaceOrientationPortraitUpsideDown</string>
		<string>UIInterfaceOrientationLandscapeLeft</string>
		<string>UIInterfaceOrientationLandscapeRight</string>
	</array>
	<key>BGTaskSchedulerPermittedIdentifiers</key>
	<array>
		<string>com.transistorsoft.fetch</string>
	</array>
</dict>
</plist>
```

**Comment by christocracy** [comment]
Delete this:  that’s not how you do it.

```dart
BackgroundFetch.scheduleTask(TaskConfig(
        taskId: "com.transistorsoft.fetch",
        delay: 10000,
        periodic: false,
        forceAlarmManager: true,
        stopOnTerminate: false,
        enableHeadless: true,
      ));
```
