### ISSUE TITLE
 android.os.DeadObjectException

### ISSUE THREAD

**Issue by Sjosh-cronJ** [transistorsoft/flutter_background_fetch#39]
08-27 12:34:28.875  1000  1408  5845 I WindowManager: WIN DEATH: Window{5b1e9ac u0 com.play.playapp/com.play.playapp.MainActivity}
08-27 12:34:28.893  1000  1408  1408 W ActivityManager: Exception when unbinding service com.play.playapp/com.transistorsoft.flutter.backgroundfetch.HeadlessJobService
08-27 12:34:28.893  1000  1408  1408 W ActivityManager: android.os.DeadObjectException
08-27 12:34:28.893  1000  1408  1408 W ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
08-27 12:34:28.893  1000  1408  1408 W ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:1127)
08-27 12:34:28.893  1000  1408  1408 W ActivityManager: 	at android.app.IApplicationThread$Stub$Proxy.scheduleUnbindService(IApplicationThread.java:1100)
08-27 12:34:28.893  1000  1408  1408 W ActivityManager: 	at com.android.server.am.ActiveServices.removeConnectionLocked(ActiveServices.java:3028)
08-27 12:34:28.893  1000  1408  1408 W ActivityManager: 	at com.android.server.am.ActiveServices.unbindServiceLocked(ActiveServices.java:1815)
08-27 12:34:28.893  1000  1408  1408 W ActivityManager: 	at com.android.server.am.ActivityManagerService.unbindService(ActivityManagerService.java:21438)
08-27 12:34:28.893  1000  1408  1408 W ActivityManager: 	at android.app.ContextImpl.unbindService(ContextImpl.java:1707)
08-27 12:34:28.893  1000  1408  1408 W ActivityManager: 	at com.android.server.job.JobServiceContext.closeAndCleanupJobLocked(JobServiceContext.java:783)
08-27 12:34:28.893  1000  1408  1408 W ActivityManager: 	at com.android.server.job.JobServiceContext.onServiceDisconnected(JobServiceContext.java:452)
08-27 12:34:28.893  1000  1408  1408 W ActivityManager: 	at android.app.LoadedApk$ServiceDispatcher.doDeath(LoadedApk.java:1749)
08-27 12:34:28.893  1000  1408  1408 W ActivityManager: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1764)
08-27 12:34:28.893  1000  1408  1408 W ActivityManager: 	at android.os.Handler.handleCallback(Handler.java:874)
08-27 12:34:28.893  1000  1408  1408 W ActivityManager: 	at android.os.Handler.dispatchMessage(Handler.java:100)
08-27 12:34:28.893  1000  1408  1408 W ActivityManager: 	at android.os.Looper.loop(Looper.java:198)
08-27 12:34:28.893  1000  1408  1408 W ActivityManager: 	at com.android.server.SystemServer.run(SystemServer.java:479)
08-27 12:34:28.893  1000  1408  1408 W ActivityManager: 	at com.android.server.SystemServer.main(SystemServer.java:307)
08-27 12:34:28.893  1000  1408  1408 W ActivityManager: 	at java.lang.reflect.Method.invoke(Native Method)
08-27 12:34:28.893  1000  1408  1408 W ActivityManager: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-27 12:34:28.893  1000  1408  1408 W ActivityManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:856)

**Comment by Sjosh-cronJ** [comment]
Hey crish I am encountering this issue when I route from one page to another from 10-12 times.
