### ISSUE TITLE
[BUG] ExceptionInInitializerError caused by NullPointerException in Release

### ISSUE THREAD

**Issue by flaviup** [transistorsoft/flutter_background_fetch#64]
**Your Environment**
* Plugin version:
* Platform: Android
* OS version: 8.1
* Device manufacturer / model: OnePlus
* Flutter info (`flutter info`, `flutter doctor`): Flutter v1.13.2 on macOS
* Plugin config

**To Reproduce**
flutter_background_fetch plugin is crashing the app in release at initialization. (The debug version is fine.)

**Debug logs**
- Android: `$ adb logcat`
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sentrybrite.livealarm, PID: 3730
    java.lang.ExceptionInInitializerError
        at com.transistorsoft.locationmanager.b.a.s(Unknown Source:0)
        at d.f.a.a.b.<init>(Unknown Source:32)
        at d.f.a.a.b.a(Unknown Source:2)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source:71)
        at com.sentrybrite.livealarm.MainActivity.b(Unknown Source:5)
        at e.a.c.a.e.a(Unknown Source:64)
        at e.a.c.a.d.onCreate(Unknown Source:22)
        at android.app.Activity.performCreate(Activity.java:7041)
        at android.app.Activity.performCreate(Activity.java:7032)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1231)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2864)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2989)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6753)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
        at d.f.c.a.a(Unknown Source:27)
        at com.transistorsoft.locationmanager.b.a.<clinit>(Unknown Source:2)
        at com.transistorsoft.locationmanager.b.a.s(Unknown Source:0) 
        at d.f.a.a.b.<init>(Unknown Source:32) 
        at d.f.a.a.b.a(Unknown Source:2) 
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(Unknown Source:71) 
        at com.sentrybrite.livealarm.MainActivity.b(Unknown Source:5) 
        at e.a.c.a.e.a(Unknown Source:64) 
        at e.a.c.a.d.onCreate(Unknown Source:22) 
        at android.app.Activity.performCreate(Activity.java:7041) 
        at android.app.Activity.performCreate(Activity.java:7032) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1231) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2864) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2989) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6753) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 

**Additional context**

**Comment by christocracy** [comment]
>Plugin version:

>Flutter v1.13.2 

I'm on stable channel:
`[✓] Flutter (Channel stable, v1.12.13+hotfix.5`

Have you [migrated your app](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)?

**Comment by flaviup** [comment]
Hi, the issue is for flutter_background_geolocation_firebase and flutter_background_geolocation projects. I've mistakenly thought is an issue for flutter_background_fetch. I also changed to Flutter v1.12.13+hotfix.5 on the stable channel and migrated the app.

**Comment by flaviup** [comment]
Fixed the problem in my project after setting:
shrinkResources false
minifyEnabled false
useProguard false

and adding 

Project background_geolocation = project(':flutter_background_geolocation')
apply from: "${background_geolocation.projectDir}/background_geolocation.gradle"

**Comment by christocracy** [comment]
See the changelog.  Have you migrated your app for flutter 1.12?

The version in master has been updated to the new v2 plugin api.  Not yet released.  I’m waiting for someone to test it.  See readme for how to install plugin from master branch.

**Comment by christocracy** [comment]
@flaviup It's important you send me the following information:
- Plugin version?
- [Have you migrated your Flutter app?](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)
