### ISSUE TITLE
Crashing on Android

### ISSUE THREAD

**Issue by Faiyyaz** [transistorsoft/flutter_background_fetch#65]
**Your Environment**
* Plugin version: ^0.4.0
* Platform: iOS or Android Android
* OS version: Android 6
* Device manufacturer / model: LGE Nexus 5X
* Flutter info (`flutter info`, `flutter doctor`):
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G103, locale en-GB)
    • Flutter version 1.12.13+hotfix.5 at /Users/faiyyazkhatri/StudioProjects/Flutter/SDK/flutter
    • Framework revision 27321ebbad (9 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/faiyyazkhatri/Library/Android/sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/faiyyazkhatri/Library/Android/sdk/
    • ANDROID_SDK_ROOT = /Users/faiyyazkhatri/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    ! No devices available
```
* Plugin config

```
// Platform messages are asynchronous, so we initialize in an async method.
  Future<void> initPlatformState() async {
    // Load persisted fetch events from SharedPreferences
    SharedPreferences prefs = await SharedPreferences.getInstance();
    String json = prefs.getString(EVENTS_KEY);
    if (json != null) {
      setState(() {
        _events = jsonDecode(json).cast<String>();
      });
    }

    // Configure BackgroundFetch.
    BackgroundFetch.configure(
            BackgroundFetchConfig(
                minimumFetchInterval: 15,
                stopOnTerminate: false,
                startOnBoot: true,
                enableHeadless: true,
                requiresBatteryNotLow: false,
                requiresCharging: false,
                requiresStorageNotLow: false,
                requiresDeviceIdle: false,
                requiredNetworkType: BackgroundFetchConfig.NETWORK_TYPE_NONE),
            _onBackgroundFetch)
        .then((int status) {
      print('[BackgroundFetch] configure success: $status');
      setState(() {
        _status = status;
      });
    }).catchError((e) {
      print('[BackgroundFetch] configure ERROR: $e');
      setState(() {
        _status = e;
      });
    });

    // Optionally query the current BackgroundFetch status.
    int status = await BackgroundFetch.status;
    setState(() {
      _status = status;
    });

    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;
  }

  void _onBackgroundFetch() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();

    // This is the fetch-event callback.
    print('[BackgroundFetch] Event received');
    setState(() {
      _events.insert(0, new DateTime.now().toString());
    });
    // Persist fetch events in SharedPreferences
    prefs.setString(EVENTS_KEY, jsonEncode(_events));

    // IMPORTANT:  You must signal completion of your fetch task or the OS can punish your app
    // for taking too long in the background.
    BackgroundFetch.finish();
  }

  const EVENTS_KEY = "fetch_events";

/// This "Headless Task" is run when app is terminated.
void backgroundFetchHeadlessTask() async {
  print('[BackgroundFetch] Headless event received.');

  SharedPreferences prefs = await SharedPreferences.getInstance();

  // Read fetch_events from SharedPreferences
  List<String> events = [];
  String json = prefs.getString(EVENTS_KEY);
  if (json != null) {
    events = jsonDecode(json).cast<String>();
  }
  // Add new event.
  events.insert(0, new DateTime.now().toString() + ' [Headless]');
  // Persist fetch events in SharedPreferences
  prefs.setString(EVENTS_KEY, jsonEncode(events));

  BackgroundFetch.finish();
}

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
  SystemChrome.setSystemUIOverlayStyle(
      SystemUiOverlayStyle(statusBarColor: Colors.transparent));
  // Set `enableInDevMode` to true to see reports while in debug mode
  // This is only to be used for confirming that reports are being
  // submitted as expected. It is not intended to be used for everyday
  // development.
  Crashlytics.instance.enableInDevMode = true;

  runApp(MyApp());

  // Register to receive BackgroundFetch events after app is terminated.
  // Requires {stopOnTerminate: false, enableHeadless: true}
  BackgroundFetch.registerHeadlessTask(backgroundFetchHeadlessTask);
}
```

**To Reproduce**
Don't know i am getting reports of crash from crashlytics

**Debug logs**
- Android:
```
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'android.content.Context io.flutter.plugin.common.PluginRegistry$Registrar.context()' on a null object reference
       at com.transistorsoft.flutter.backgroundfetch.b.a(SourceFile:2)
       at c.a.c.a.b(SourceFile:2)
       at ooo.intro.app.MainActivity.onCreate(SourceFile:2)
       at android.app.Activity.performCreate(Activity.java:6251)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by christocracy** [comment]
There will be some pain during the transition to Flutter `1.12`.  [0.40.0](https://github.com/transistorsoft/flutter_background_fetch/blob/master/CHANGELOG.md#040---2019-12-17) is an upgrade to Flutter's new "V2" plugin api.

Have you [upgraded your Flutter app](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)?

Please show me your Android app's `Application.java` (or `Application.kt` if using Kotlin).

**Comment by Faiyyaz** [comment]
Here is my application class

```
import io.flutter.app.FlutterApplication
import android.content.Context
import androidx.multidex.MultiDex
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugins.GeneratedPluginRegistrant
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService

class App : FlutterApplication(), PluginRegistry.PluginRegistrantCallback {

    override fun attachBaseContext(base: Context) {
        super.attachBaseContext(base)
        MultiDex.install(this)
    }

    override fun onCreate() {
        super.onCreate()
        FlutterFirebaseMessagingService.setPluginRegistrant(this)
    }

    override fun registerWith(p0: PluginRegistry?) {
        GeneratedPluginRegistrant.registerWith(p0)
    }
}
```

**Comment by christocracy** [comment]
I need the answer to this question:
>Have you [upgraded your Flutter app](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)?

**Comment by christocracy** [comment]
When the new Flutter Plugin API, you no longer need to do anything in `MainApplication.java`.

**Comment by christocracy** [comment]
Actually, it's clear from your `Application.kt` that you haven't migrated your app yet.  I *highly* suggest you migrate your app to the new API, as linked above.  A freshly generated Flutter app's `Application.kt` looks like this:
```kotlin
package com.example.foo

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
```

**Comment by Faiyyaz** [comment]
I have updated flutter to new stable version which is 1.12.13

**Comment by christocracy** [comment]
[Read this](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects).  There's more to upgrading to the new API than simply upgrading the Flutter SDK.

- This sort of thing is no longer necessary; with the new API, it's all *automatic*
```
FlutterFirebaseMessagingService.setPluginRegistrant(this)
```

But you *must* upgrade your Flutter app as noted in the link I've posted multiple times above.

**Comment by christocracy** [comment]
`Application.kt`:
- Old *deprecated* API 
```kotlin
override fun registerWith(p0: PluginRegistry?) {
        GeneratedPluginRegistrant.registerWith(p0)
    }
```
- New API
```kotlin
override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
```

**Comment by Faiyyaz** [comment]
Ok thanks for the help.

I will do the necessary changes and try again

**Comment by logoped583st** [comment]
I have the same issue.

**Comment by logoped583st** [comment]
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G2022, locale en-BY)
    • Flutter version 1.12.13+hotfix.5 at /Users/ws-071-11b/Documents/flutter
    • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ws-071-11b/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/ws-071-11b/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6071332/Android Studio 3.6 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/ws-071-11b/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6071332/Android Studio 3.6 Preview.app/Contents
    • Flutter plugin version 42.2.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    • IntelliJ at /Users/ws-071-11b/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • SM A720F                  • 5210f39cec5b5445 • android-arm64 • Android 8.0.0 (API 26) (emulator)
    • Android SDK built for x86 • emulator-5554    • android-x86   • Android 7.1.1 (API 25) (emulator)
```

**Comment by christocracy** [comment]
All the steps to migrate the Flutter Android app is [here](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects), including **required** modification to `AndroidManifest.xml`, particularly this:
```xml
<meta-data
    android:name="flutterEmbedding"
    android:value="2" />
```

**Comment by Faiyyaz** [comment]
I have created a new project and added the library around 5 hours back still no event on android. How much time does it take to reflect?
