### ISSUE TITLE
How to use HTTP requests on "backgroundFetchHeadlessTask" method

### ISSUE THREAD

**Issue by menqi20** [transistorsoft/flutter_background_fetch#7]
hi,How to use HTTP requests on "backgroundFetchHeadlessTask" method
i use the package:dio/dio.dart  ，Not succeeding, always prompting timeouts
thanks!

**Comment by christocracy** [comment]
Show me your code.

**Comment by menqi20** [comment]
`import 'dart:io';
import 'package:dio/dio.dart';

import 'package:shared_preferences/shared_preferences.dart';
import 'package:background_fetch/background_fetch.dart';

const EVENTS_KEY = "fetch_events";

Options options= new Options(
  baseUrl:"http://www.vdh.cx/",
  connectTimeout:5000,
  receiveTimeout:5000,
  responseType: ResponseType.JSON,
  contentType: ContentType.parse("application/x-www-form-urlencoded"),
  //headers: {"content-type":"application/x-www-form-urlencoded"}
);
Dio dio = new Dio(options);

/// This "Headless Task" is run when app is terminated.
void backgroundFetchHeadlessTask() async {
  print('[BackgroundFetch] Headless event received1.');
  SharedPreferences prefs = await SharedPreferences.getInstance();

  var response=await dio.post("",data: {'do': 'user.testfun', 'data': 'foo'});
  print('hello');
  // Read fetch_events from SharedPreferences
  List<String> events = [];
  String json = prefs.getString(EVENTS_KEY);
  if (json != null) {
    events = jsonDecode(json).cast<String>();
  }
  // Add new event.
  events.insert(0, new DateTime.now().toString() + ' [Headless]');
  // Persist fetch events in SharedPreferences
  prefs.setString(EVENTS_KEY, jsonEncode(events));

  BackgroundFetch.finish();
}`

**Comment by christocracy** [comment]
Try putting `Dio dio = new Dio(options);` into the headless-task.

```dart
void backgroundFetchHeadlessTask() async {
  Dio dio = new Dio(options);
  .
  .
  .
}
```

**Comment by menqi20** [comment]
oh,I've tested this way, but it still doesn't seem to work.
Does this package not support headless running?

**Comment by christocracy** [comment]
>Does this package not support headless running?

Why do you think the plugin has a method `#registerHeadlessTask`?  Your problem is an HTTP Connect timeout.

**Comment by christocracy** [comment]
Have you tried increasing your HTTP connect timeout?

**Comment by menqi20** [comment]
I've set a timeout of 5 seconds now, and I've tried not to set a timeout. It's all unsuccessful.

**Comment by christocracy** [comment]
I will reproduce using your code.

**Comment by christocracy** [comment]
And btw, are you sure your host is *valid*?
```
$ ping http://www.vdh.cx
ping: cannot resolve http://www.vdh.cx: Unknown host
```

**Comment by christocracy** [comment]
oops, my bad adding `http://` to ping.

**Comment by menqi20** [comment]
This website is normal here. Can you try to change it to your local URL to see if it is normal?
and I tried using another URL test, such as httpbin.org,  was not normal.

**Comment by menqi20** [comment]
`D/ViewRootImpl@7776267[MainActivity](29632): mHardwareRenderer.destroy()#4
D/ViewRootImpl@7776267[MainActivity](29632): dispatchDetachedFromWindow
D/InputTransport(29632): Input channel destroyed: fd=77
D/TSBackgroundFetch(29632): - Background Fetch event received
D/TSBackgroundFetch(29632): - finish
D/TSBackgroundFetch(29632): - jobFinished
D/TSBackgroundFetch(29632): HeadlessJobService onStartJob
D/TSBackgroundFetch(29632): 💀 [HeadlessTask]
D/TSBackgroundFetch(29632): [HeadlessTask] waiting for client to initialize
I/TSBackgroundFetch(29632): $ initialized
I/flutter (29632): [BackgroundFetch] Headless event received1.
E/flutter (29632): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (29632): SocketException: OS Error: Connection timed out, errno = 110, address = httpbin.org, port = 37098
E/flutter (29632): #0      backgroundFetchHeadlessTask (package:background_fetch_example/main.dart:35:17)
E/flutter (29632): <asynchronous suspension>
E/flutter (29632): #1      _headlessCallbackDispatcher.<anonymous closure> (package:background_fetch/background_fetch.dart:353:15)
E/flutter (29632): <asynchronous suspension>
E/flutter (29632): #2      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:344:55)
E/flutter (29632): <asynchronous suspension>
E/flutter (29632): #3      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:312:54)
E/flutter (29632): #4      BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:67:33)
E/flutter (29632): <asynchronous suspension>
E/flutter (29632): #5      _invoke3 (dart:ui/hooks.dart:196:13)
E/flutter (29632): #6      _dispatchPlatformMessage (dart:ui/hooks.dart:105:5)`

**Comment by menqi20** [comment]
The above run log, which I run using the httclient of packages dart: IO
`var httpClient = new HttpClient();
  var uri = new Uri.http(
      'httpbin.org', '/', {});
  var request = await httpClient.getUrl(uri);
  var response = await request.close();`

**Comment by christocracy** [comment]
Works for me:

```
01-12 10:55:35.440 18588 18588 D TSBackgroundFetch: - Background Fetch event received
01-12 10:55:35.448 18588 18588 D TSBackgroundFetch: - finish
01-12 10:55:35.448 18588 18588 D TSBackgroundFetch: - jobFinished
01-12 10:55:35.480 18588 18588 D TSBackgroundFetch: HeadlessJobService onStartJob
01-12 10:55:35.481 18588 18588 D TSBackgroundFetch: 💀 [HeadlessTask]
01-12 10:55:35.485 18588 18607 I flutter : [BackgroundFetch] Headless event received.
01-12 10:55:36.852 18588 18607 I flutter : hello: [data]={code: 1, msg: }
01-12 10:55:36.892 18588 18588 D TSBackgroundFetch: - finish
01-12 10:55:36.892 18588 18588 D TSBackgroundFetch: HeadlessJobService jobFinished
```

**Comment by menqi20** [comment]
Is there anything wrong with my setup? I used your example. I saw your submission record in the background database.

**Comment by menqi20** [comment]
E:\code\flutter\demo\flutter_background_fetch>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] Connected device (1 available)

• No issues found!

E:\code\flutter\demo\flutter_background_fetch>

**Comment by christocracy** [comment]
And it works when I instantiate `dio` *outside* of `backgroundFetchHeadlessTask`:

```dart
Options options= new Options(
  baseUrl:"http://www.vdh.cx/",
  connectTimeout:5000,
  receiveTimeout:5000,
  responseType: ResponseType.JSON,
  contentType: ContentType.parse("application/x-www-form-urlencoded"),
  //headers: {"content-type":"application/x-www-form-urlencoded"}
);

Dio dio = new Dio(options);

/// This "Headless Task" is run when app is terminated.
void backgroundFetchHeadlessTask() async {
  print('[BackgroundFetch] Headless event received.');

  var response=await dio.post("",data: {'do': 'user.testfun', 'data': 'foo'});
  print('hello: ' + response.toString());
}

```

**Comment by christocracy** [comment]
Have you tried your "`dio` request in the [primary fetch-callback](https://github.com/transistorsoft/flutter_background_fetch/blob/master/example/lib/main.dart#L75) (ie: non-headless case)?

What device model / os are you testing this on?

**Comment by menqi20** [comment]
I tested it in this method  `void _onBackgroundFetch() async {}`  ,It's normal.
My device is Samsung S6+ edge

**Comment by menqi20** [comment]
this log run in _onBackgroundFetch method
```yncing files to device SM G9280...
E/flutter ( 3219): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 3219): 'dart:isolate/runtime/libtimer_impl.dart': Failed assertion: line 433: '<optimized out>': is not true.
E/flutter ( 3219): #0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
E/flutter ( 3219): #1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
E/flutter ( 3219): #2      _Timer._cancelWakeup (dart:isolate/runtime/libtimer_impl.dart:433:12)
E/flutter ( 3219): #3      _Timer._notifyEventHandler (dart:isolate/runtime/libtimer_impl.dart:299:7)
E/flutter ( 3219): #4      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:419:5)
E/flutter ( 3219): #5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
D/TSBackgroundFetch( 3219): - Background Fetch event received
I/flutter ( 3219): [BackgroundFetch] Event received
I/flutter ( 3219): hello: [data]={code: 1, msg: }
D/TSBackgroundFetch( 3219): - finish
D/TSBackgroundFetch( 3219): - jobFinished```

**Comment by menqi20** [comment]
```void _onBackgroundFetch() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();

    // This is the fetch-event callback.
    print('[BackgroundFetch] Event received');
    var response=await dio.post("",data: {"do": "user.testfun", "data": "foo"});
    print('hello: ' + response.toString());
    setState(() {
      _events.insert(0, new DateTime.now().toString());
    });```

**Comment by christocracy** [comment]
On your Samsung S6 Settings, show me a screenshot of the "Battery" screen.

**Comment by menqi20** [comment]
[http://www.vdh.cx/20190113001543.png  ](url)
This is a screenshot of the battery picture.

**Comment by christocracy** [comment]
- Power saving mode:  *OFF*
- Unmonitored apps:  Add the background_fetch app to be "unmonitored"

**Comment by menqi20** [comment]
Is HTTP request timeout related to batteries ？

**Comment by christocracy** [comment]
Your battery-saving conditions might be getting applied since your battery is low (32%), preventing HTTP requests.

**Comment by menqi20** [comment]
I'm going to use this package to upload location information regularly，But location needs to use Google Framework，We don't have this condition here.

**Comment by christocracy** [comment]
`flutter_background_geolocation` uses `play-services:location`.

It's designed for aggressive tracking of devices in background / terminated states.  It's primarily designed for "fleet-tracking" (eg: taxi app, deliver app, emergency response) / fitness use-cases.
![](https://dl.dropboxusercontent.com/s/10u2729yrddv2g3/Screenshot%202019-01-12%2011.36.13.png?dl=1)

**Comment by menqi20** [comment]
It‘s great ,if could support the use in China.

**Comment by christocracy** [comment]
Will never work in China until Google Play Services is supported.

**Comment by pilojanmobile** [comment]
problem is SharedPreferences, without SharedPreferences working fine,
